import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { workspaceMigrationsFolder } from '@rentable/workspace-migrations';

/**
 * That the workspace migrations have one home, and that everything writes to and reads from it.
 *
 * **The SQL a workspace database is built from lives in `packages/workspace-migrations`**, because
 * the same set builds a local workspace here and a hosted one in `apps/control-plane` — decision
 * 06 on `a-workspace-follows-its-user`. A second copy is what this file exists to prevent, and it
 * lives in this package because that is where the commits that would break it land.
 */
const desktop = fileURLToPath(new URL('../../../../../', import.meta.url));

const folder = fileURLToPath(workspaceMigrationsFolder);

/**
 * The generator writes where the appliers read.
 *
 * `pnpm db:generate:desktop` emitting into a directory nobody applies is silent: the tree keeps building,
 * the tests keep passing against the migrations that already exist, and the new one is simply
 * never applied anywhere. Nothing else in this repository would notice.
 */
test('drizzle-kit generates into the workspace migrations package', async () => {
	const config = await readFile(path.join(desktop, 'drizzle.config.ts'), 'utf8');
	const out = /out:\s*'([^']+)'/.exec(config)?.[1];

	assert.ok(out, 'drizzle.config.ts names no output directory');
	assert.equal(path.resolve(desktop, out), path.resolve(folder));
});

/**
 * `tauri/migrations/` is generated by `tauri/build.rs` and must not become a second tracked copy.
 *
 * It exists because the Rust runner takes a directory and Tauri bundles one; it is gitignored, and
 * this is what would notice somebody committing it back.
 */
test('the desktop keeps no tracked copy of the migrations', async () => {
	const ignore = await readFile(path.join(desktop, '.gitignore'), 'utf8');

	assert.match(ignore, /^\/tauri\/migrations\/$/m, 'tauri/migrations is not ignored');
});

// The package is where the count that both sides call the schema version comes from.
test('the package ships the migrations this application is built from', async () => {
	const shipped = (await readdir(folder)).filter((name) => name.endsWith('.sql'));

	assert.ok(shipped.length > 0, 'the workspace migrations package ships no sql');
	assert.match(path.resolve(folder), /workspace-migrations/);
});
