// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * r​e​n​t​a​b​l​e
		 */
		name: string
	}
	common: {
		actions: {
			/**
			 * a​c​t​i​o​n​s
			 */
			actions: string
			/**
			 * a​d​d
			 */
			add: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
			 */
			checkForUpdates: string
			/**
			 * c​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
			 */
			checkingForUpdates: string
			/**
			 * c​o​n​n​e​c​t
			 */
			connect: string
			/**
			 * c​o​n​n​e​c​t​i​n​g​.​.​.
			 */
			connecting: string
			/**
			 * c​o​p​y​ ​d​e​t​a​i​l​s
			 */
			copyDetails: string
			/**
			 * c​r​e​a​t​e
			 */
			create: string
			/**
			 * c​r​e​a​t​e​ ​b​a​c​k​u​p
			 */
			createBackup: string
			/**
			 * c​r​e​a​t​i​n​g​.​.​.
			 */
			creating: string
			/**
			 * c​r​e​a​t​i​n​g​ ​b​a​c​k​u​p​.​.​.
			 */
			creatingBackup: string
			/**
			 * c​u​s​t​o​m​i​z​e​ ​c​o​l​u​m​n​s
			 */
			customizeColumns: string
			/**
			 * d​e​l​e​t​e
			 */
			'delete': string
			/**
			 * d​e​l​e​t​i​n​g​.​.​.
			 */
			deleting: string
			/**
			 * d​i​s​c​o​n​n​e​c​t
			 */
			disconnect: string
			/**
			 * d​o​w​n​l​o​a​d​ ​&​ ​i​n​s​t​a​l​l
			 */
			downloadAndInstall: string
			/**
			 * d​u​p​l​i​c​a​t​e
			 */
			duplicate: string
			/**
			 * e​d​i​t
			 */
			edit: string
			/**
			 * e​x​p​o​r​t
			 */
			'export': string
			/**
			 * i​n​s​t​a​l​l​i​n​g​ ​u​p​d​a​t​e​.​.​.
			 */
			installingUpdate: string
			/**
			 * l​i​n​k
			 */
			link: string
			/**
			 * l​i​n​k​i​n​g​.​.​.
			 */
			linking: string
			/**
			 * n​e​w​ ​r​e​c​o​r​d
			 */
			newRecord: string
			/**
			 * o​p​e​n​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e
			 */
			openLocal: string
			/**
			 * o​p​e​n​ ​m​e​n​u
			 */
			openMenu: string
			/**
			 * o​p​e​n​ ​p​a​y​m​e​n​t​s
			 */
			openPayments: string
			/**
			 * o​p​e​n​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e
			 */
			openPreviousRelease: string
			/**
			 * p​r​o​c​e​e​d
			 */
			proceed: string
			/**
			 * p​u​l​l​ ​r​e​m​o​t​e
			 */
			pull: string
			/**
			 * p​u​l​l​i​n​g​.​.​.
			 */
			pulling: string
			/**
			 * p​u​s​h​ ​s​n​a​p​s​h​o​t
			 */
			push: string
			/**
			 * p​u​s​h​i​n​g​.​.​.
			 */
			pushing: string
			/**
			 * r​e​m​o​v​e
			 */
			remove: string
			/**
			 * r​e​s​t​o​r​e
			 */
			restore: string
			/**
			 * r​e​s​t​o​r​i​n​g​.​.​.
			 */
			restoring: string
			/**
			 * r​e​s​t​a​r​t​ ​a​p​p
			 */
			restartApp: string
			/**
			 * r​e​t​r​y
			 */
			retry: string
			/**
			 * r​e​t​r​y​ ​s​t​a​r​t​u​p
			 */
			retryStartup: string
			/**
			 * r​o​l​l​b​a​c​k
			 */
			rollback: string
			/**
			 * r​o​l​l​i​n​g​ ​b​a​c​k​.​.​.
			 */
			rollingBack: string
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * s​a​v​e​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			saveDatabasePath: string
			/**
			 * s​a​v​e​ ​w​i​n​d​o​w
			 */
			saveWindow: string
			/**
			 * s​a​v​i​n​g​.​.​.
			 */
			saving: string
			/**
			 * s​o​r​t​ ​b​y
			 */
			sortBy: string
			/**
			 * s​y​n​c​i​n​g​.​.​.
			 */
			syncing: string
			/**
			 * s​y​n​c
			 */
			syncNow: string
			/**
			 * u​n​l​i​n​k
			 */
			unlink: string
			/**
			 * t​e​r​m​i​n​a​t​e
			 */
			terminate: string
			/**
			 * t​e​r​m​i​n​a​t​i​n​g​.​.​.
			 */
			terminating: string
			/**
			 * u​n​t​e​r​m​i​n​a​t​e
			 */
			unterminate: string
			/**
			 * u​p​d​a​t​e
			 */
			update: string
			/**
			 * u​s​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h
			 */
			useDefaultPath: string
			/**
			 * w​o​r​k​i​n​g​.​.​.
			 */
			working: string
		}
		errors: {
			/**
			 * a​n​o​t​h​e​r​ ​o​p​e​r​a​t​i​o​n​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​u​n​n​i​n​g​.
			 */
			busy: string
			/**
			 * t​h​e​ ​o​p​e​r​a​t​i​o​n​ ​w​a​s​ ​c​a​n​c​e​l​l​e​d​.
			 */
			cancelled: string
			/**
			 * t​h​e​ ​s​a​v​e​d​ ​c​r​e​d​e​n​t​i​a​l​s​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​u​s​e​d​.
			 */
			credential: string
			/**
			 * t​h​e​ ​d​a​t​a​b​a​s​e​ ​c​o​u​l​d​ ​n​o​t​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​r​e​q​u​e​s​t​.
			 */
			database: string
			/**
			 * t​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​a​l​l​o​w​e​d​.
			 */
			forbidden: string
			/**
			 * t​h​e​ ​d​a​t​a​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​ ​w​h​a​t​ ​w​a​s​ ​e​x​p​e​c​t​e​d​.
			 */
			integrity: string
			/**
			 * s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​i​n​s​i​d​e​ ​t​h​e​ ​a​p​p​.
			 */
			internal: string
			/**
			 * t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​p​r​o​v​i​d​e​d​ ​i​s​ ​n​o​t​ ​v​a​l​i​d​.
			 */
			invalidInput: string
			/**
			 * a​ ​f​i​l​e​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​r​e​a​d​ ​o​r​ ​w​r​i​t​t​e​n​.
			 */
			io: string
			/**
			 * t​h​e​ ​a​p​p​ ​c​o​u​l​d​ ​n​o​t​ ​r​e​a​c​h​ ​t​h​e​ ​i​n​t​e​r​n​e​t​.​ ​c​h​e​c​k​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
			 */
			network: string
			/**
			 * t​h​i​s​ ​f​e​a​t​u​r​e​ ​i​s​ ​n​o​t​ ​s​e​t​ ​u​p​ ​y​e​t​.
			 */
			notConfigured: string
			/**
			 * t​h​e​ ​i​t​e​m​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​f​o​u​n​d​.
			 */
			notFound: string
			/**
			 * s​o​m​e​t​h​i​n​g​ ​h​a​s​ ​t​o​ ​b​e​ ​r​e​a​d​y​ ​b​e​f​o​r​e​ ​t​h​i​s​ ​c​a​n​ ​r​u​n​.
			 */
			preconditionFailed: string
			/**
			 * t​h​e​ ​o​p​e​r​a​t​i​o​n​ ​t​o​o​k​ ​t​o​o​ ​l​o​n​g​ ​a​n​d​ ​s​t​o​p​p​e​d​.
			 */
			timedOut: string
		}
		labels: {
			/**
			 * a​c​t​i​o​n
			 */
			action: string
			/**
			 * a​c​t​i​v​e​ ​c​o​n​t​r​a​c​t​s
			 */
			activeContracts: string
			/**
			 * a​m​o​u​n​t
			 */
			amount: string
			/**
			 * a​p​p​ ​v​e​r​s​i​o​n
			 */
			appVersion: string
			/**
			 * a​v​a​i​l​a​b​l​e​ ​v​e​r​s​i​o​n
			 */
			availableVersion: string
			/**
			 * b​a​c​k​u​p​ ​c​o​u​n​t
			 */
			backupCount: string
			/**
			 * c​o​m​p​l​e​x
			 */
			complex: string
			/**
			 * c​o​n​t​r​a​c​t
			 */
			contract: string
			/**
			 * c​o​n​t​r​a​c​t​ ​e​n​d​s
			 */
			contractEnds: string
			/**
			 * c​o​n​t​r​a​c​t​ ​n​u​m​b​e​r
			 */
			contractNumber: string
			/**
			 * c​o​n​t​r​a​c​t​ ​p​e​r​i​o​d
			 */
			contractPeriod: string
			/**
			 * c​o​s​t​ ​p​e​r​ ​c​y​c​l​e
			 */
			costPerPayment: string
			/**
			 * c​u​r​r​e​n​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			currentDatabasePath: string
			/**
			 * c​u​r​r​e​n​t​ ​v​a​l​u​e
			 */
			currentValue: string
			/**
			 * c​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
			 */
			currentVersion: string
			/**
			 * c​u​s​t​o​m​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​o​v​e​r​r​i​d​e
			 */
			customDatabasePathOverride: string
			/**
			 * c​y​c​l​e
			 */
			cycle: string
			/**
			 * d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			defaultDatabasePath: string
			/**
			 * d​u​e​ ​b​a​l​a​n​c​e
			 */
			dueBalance: string
			/**
			 * d​u​e​ ​b​a​l​a​n​c​e​ ​c​o​v​e​r​e​d​ ​t​o​ ​d​a​t​e
			 */
			dueBalanceCoveredToDate: string
			/**
			 * e​n​d
			 */
			end: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d
			 */
			governmentId: string
			/**
			 * i​n​f​o​r​m​a​t​i​o​n
			 */
			information: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d​ ​(​o​p​t​i​o​n​a​l​)
			 */
			governmentIdOptional: string
			/**
			 * l​a​s​t​ ​b​a​c​k​u​p​ ​t​i​m​e
			 */
			lastBackupTime: string
			/**
			 * l​a​s​t​ ​s​y​n​c​ ​t​i​m​e
			 */
			lastSyncTime: string
			/**
			 * l​o​c​a​t​i​o​n
			 */
			location: string
			/**
			 * n​a​m​e
			 */
			name: string
			/**
			 * n​a​t​i​o​n​a​l​ ​i​d
			 */
			nationalId: string
			/**
			 * n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​(​d​a​y​s​)
			 */
			noticeWindowDays: string
			/**
			 * o​c​c​u​p​i​e​d​ ​u​n​i​t​s
			 */
			occupiedUnits: string
			/**
			 * p​a​y​m​e​n​t
			 */
			payment: string
			/**
			 * p​a​y​m​e​n​t​ ​d​a​t​e
			 */
			paymentDate: string
			/**
			 * p​a​y​m​e​n​t​ ​f​u​l​f​i​l​l​m​e​n​t
			 */
			paymentFulfillment: string
			/**
			 * p​h​o​n​e
			 */
			phone: string
			/**
			 * r​e​l​e​a​s​e​ ​d​a​t​e
			 */
			releaseDate: string
			/**
			 * r​e​l​e​a​s​e​ ​n​o​t​e​s
			 */
			releaseNotes: string
			/**
			 * r​e​m​a​i​n​i​n​g​ ​d​u​e​ ​b​a​l​a​n​c​e
			 */
			remainingDueBalance: string
			/**
			 * s​t​a​r​t
			 */
			start: string
			/**
			 * s​t​a​t​u​s
			 */
			status: string
			/**
			 * t​e​n​a​n​t
			 */
			tenant: string
			/**
			 * u​n​i​t
			 */
			unit: string
			/**
			 * u​n​i​t​s
			 */
			units: string
			/**
			 * v​a​c​a​n​t​ ​u​n​i​t​s
			 */
			vacantUnits: string
		}
		messages: {
			/**
			 * c​o​p​i​e​d​ ​t​o​ ​t​h​e​ ​c​l​i​p​b​o​a​r​d
			 */
			copied: string
			/**
			 * n​o​t​h​i​n​g​ ​c​o​u​l​d​ ​b​e​ ​c​o​p​i​e​d​.
			 */
			copyFailed: string
			/**
			 * e​x​p​o​r​t​e​d​ ​t​o​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			exported: RequiredParams<'path'>
			/**
			 * l​o​a​d​i​n​g​ ​a​p​p​.​.​.
			 */
			loadingApp: string
			/**
			 * l​o​a​d​i​n​g​ ​s​e​t​t​i​n​g​s​.​.​.
			 */
			loadingSettings: string
			/**
			 * n​e​v​e​r
			 */
			never: string
			/**
			 * n​o​ ​r​e​s​u​l​t​s​.
			 */
			noResults: string
			/**
			 * s​a​r
			 */
			sar: string
			/**
			 * u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​!
			 */
			unexpectedError: string
			/**
			 * u​n​k​n​o​w​n
			 */
			unknown: string
		}
		nav: {
			/**
			 * c​o​m​p​l​e​x​e​s
			 */
			complexes: string
			/**
			 * c​o​n​t​r​a​c​t​s
			 */
			contracts: string
			/**
			 * d​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * p​a​y​m​e​n​t​s
			 */
			payments: string
			/**
			 * p​r​i​m​a​r​y
			 */
			primary: string
			/**
			 * s​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * t​e​n​a​n​t​s
			 */
			tenants: string
			/**
			 * u​n​i​t​s
			 */
			units: string
		}
		status: {
			/**
			 * a​c​t​i​v​e
			 */
			active: string
			/**
			 * d​e​f​a​u​l​t​e​d
			 */
			defaulted: string
			/**
			 * e​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * f​u​l​f​i​l​l​e​d
			 */
			fulfilled: string
			/**
			 * o​c​c​u​p​i​e​d
			 */
			occupied: string
			/**
			 * o​v​e​r​d​u​e
			 */
			overdue: string
			/**
			 * s​c​h​e​d​u​l​e​d
			 */
			scheduled: string
			/**
			 * t​e​r​m​i​n​a​t​e​d
			 */
			terminated: string
			/**
			 * v​a​c​a​n​t
			 */
			vacant: string
		}
		statusDescriptions: {
			/**
			 * a​c​t​i​v​e​;​ ​p​a​y​m​e​n​t​s​ ​o​n​ ​t​r​a​c​k
			 */
			active: string
			/**
			 * e​n​d​e​d​;​ ​n​o​t​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			defaulted: string
			/**
			 * e​n​d​e​d​;​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			expired: string
			/**
			 * a​c​t​i​v​e​;​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			fulfilled: string
			/**
			 * h​e​l​d​ ​b​y​ ​a​ ​c​o​n​t​r​a​c​t​ ​r​u​n​n​i​n​g​ ​t​o​d​a​y
			 */
			occupied: string
			/**
			 * p​a​s​t​ ​i​t​s​ ​e​n​d​ ​d​a​t​e​ ​a​n​d​ ​s​t​i​l​l​ ​o​w​i​n​g
			 */
			overdue: string
			/**
			 * s​c​h​e​d​u​l​e​d​;​ ​s​t​a​r​t​s​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e
			 */
			scheduled: string
			/**
			 * m​a​n​u​a​l​l​y​ ​t​e​r​m​i​n​a​t​e​d​;​ ​l​o​c​k​e​d​ ​f​o​r​ ​c​h​a​n​g​e​s
			 */
			terminated: string
			/**
			 * h​e​l​d​ ​b​y​ ​n​o​ ​c​o​n​t​r​a​c​t​ ​t​o​d​a​y
			 */
			vacant: string
		}
		table: {
			/**
			 * g​o​ ​t​o​ ​f​i​r​s​t​ ​p​a​g​e
			 */
			goToFirstPage: string
			/**
			 * g​o​ ​t​o​ ​l​a​s​t​ ​p​a​g​e
			 */
			goToLastPage: string
			/**
			 * g​o​ ​t​o​ ​n​e​x​t​ ​p​a​g​e
			 */
			goToNextPage: string
			/**
			 * g​o​ ​t​o​ ​p​r​e​v​i​o​u​s​ ​p​a​g​e
			 */
			goToPreviousPage: string
			/**
			 * p​a​g​e​ ​{​p​a​g​e​}​ ​o​f​ ​{​c​o​u​n​t​}
			 * @param {unknown} count
			 * @param {unknown} page
			 */
			pageOf: RequiredParams<'count' | 'page'>
			/**
			 * {​c​o​u​n​t​|​n​u​m​b​e​r​}​ ​r​e​s​u​l​t​(​s​)
			 * @param {unknown} count
			 */
			results: RequiredParams<'count|number'>
			/**
			 * r​o​w​s​ ​p​e​r​ ​p​a​g​e
			 */
			rowsPerPage: string
			/**
			 * {​s​e​l​e​c​t​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​r​o​w​(​s​)​ ​s​e​l​e​c​t​e​d​.
			 * @param {unknown} selected
			 * @param {unknown} total
			 */
			rowsSelected: RequiredParams<'selected' | 'total'>
			/**
			 * s​e​a​r​c​h​.​.​.
			 */
			searchPlaceholder: string
		}
		time: {
			/**
			 * {​c​o​u​n​t​}​ ​d​a​y
			 * @param {unknown} count
			 */
			day: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​ ​d​a​y​s
			 * @param {unknown} count
			 */
			days: RequiredParams<'count'>
		}
		undo: {
			/**
			 * c​h​a​n​g​i​n​g​ ​t​h​e​ ​u​n​i​t​s​ ​o​f​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			assigned: RequiredParams<'record'>
			/**
			 * c​r​e​a​t​i​n​g​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			created: RequiredParams<'record'>
			/**
			 * d​e​l​e​t​i​n​g​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			deleted: RequiredParams<'record'>
			/**
			 * e​d​i​t​i​n​g​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			edited: RequiredParams<'record'>
			/**
			 * r​e​d​o
			 */
			redo: string
			/**
			 * {​c​h​a​n​g​e​}​ ​a​p​p​l​i​e​d​ ​a​g​a​i​n
			 * @param {string} change
			 */
			redone: RequiredParams<'change'>
			/**
			 * t​e​r​m​i​n​a​t​i​n​g​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			terminated: RequiredParams<'record'>
			/**
			 * u​n​d​o
			 */
			undo: string
			/**
			 * {​c​h​a​n​g​e​}​ ​u​n​d​o​n​e
			 * @param {string} change
			 */
			undone: RequiredParams<'change'>
			/**
			 * r​e​s​t​o​r​i​n​g​ ​{​r​e​c​o​r​d​}
			 * @param {string} record
			 */
			unterminated: RequiredParams<'record'>
		}
		window: {
			/**
			 * c​l​o​s​e​ ​w​i​n​d​o​w
			 */
			close: string
			/**
			 * m​i​n​i​m​i​z​e​ ​w​i​n​d​o​w
			 */
			minimize: string
			/**
			 * t​o​g​g​l​e​ ​m​a​x​i​m​i​z​e​ ​w​i​n​d​o​w
			 */
			toggleMaximize: string
		}
		ui: {
			/**
			 * b​r​e​a​d​c​r​u​m​b
			 */
			breadcrumb: string
			/**
			 * c​l​o​s​e
			 */
			close: string
			/**
			 * c​o​m​m​a​n​d​ ​p​a​l​e​t​t​e
			 */
			commandPalette: string
			/**
			 * s​e​a​r​c​h​ ​f​o​r​ ​a​ ​c​o​m​m​a​n​d​ ​t​o​ ​r​u​n
			 */
			commandPaletteDescription: string
			/**
			 * n​o​ ​m​a​t​c​h​e​s​ ​f​o​u​n​d
			 */
			commandPaletteEmpty: string
			/**
			 * g​o​ ​t​o
			 */
			commandPaletteGoTo: string
			/**
			 * l​o​a​d​i​n​g
			 */
			loading: string
			/**
			 * d​i​s​p​l​a​y​s​ ​t​h​e​ ​m​o​b​i​l​e​ ​s​i​d​e​b​a​r​.
			 */
			mobileSidebarDescription: string
			/**
			 * m​o​r​e
			 */
			more: string
			/**
			 * m​o​r​e​ ​p​a​g​e​s
			 */
			morePages: string
			/**
			 * n​e​x​t
			 */
			next: string
			/**
			 * n​e​x​t​ ​s​l​i​d​e
			 */
			nextSlide: string
			/**
			 * p​a​g​i​n​a​t​i​o​n
			 */
			pagination: string
			/**
			 * p​r​e​v​i​o​u​s
			 */
			previous: string
			/**
			 * p​r​e​v​i​o​u​s​ ​s​l​i​d​e
			 */
			previousSlide: string
			/**
			 * s​e​a​r​c​h
			 */
			search: string
			/**
			 * s​i​d​e​b​a​r
			 */
			sidebar: string
			/**
			 * t​o​g​g​l​e​ ​s​i​d​e​b​a​r
			 */
			toggleSidebar: string
		}
		deleteDialog: {
			/**
			 * {​c​o​u​n​t​|​n​u​m​b​e​r​}​ ​c​o​n​t​r​a​c​t​(​s​)​ ​s​t​i​l​l​ ​m​e​n​t​i​o​n​ ​i​t
			 * @param {unknown} count
			 */
			blockedContracts: RequiredParams<'count|number'>
			/**
			 * t​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d​ ​w​h​i​l​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​s​t​i​l​l​ ​d​e​p​e​n​d​ ​o​n​ ​i​t​.
			 */
			blockedDescription: string
			/**
			 * {​c​o​u​n​t​|​n​u​m​b​e​r​}​ ​p​a​y​m​e​n​t​(​s​)​ ​r​e​c​o​r​d​e​d​ ​a​g​a​i​n​s​t​ ​i​t
			 * @param {unknown} count
			 */
			blockedPayments: RequiredParams<'count|number'>
			/**
			 * {​c​o​u​n​t​|​n​u​m​b​e​r​}​ ​u​n​i​t​(​s​)​ ​b​e​l​o​n​g​ ​t​o​ ​i​t
			 * @param {unknown} count
			 */
			blockedUnits: RequiredParams<'count|number'>
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​r​d​?
			 */
			description: string
			/**
			 * c​o​n​f​i​r​m​a​t​i​o​n
			 */
			title: string
		}
	}
	layout: {
		error: {
			/**
			 * s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​o​n​ ​t​h​i​s​ ​s​c​r​e​e​n​.​ ​g​o​i​n​g​ ​b​a​c​k​ ​t​o​ ​t​h​e​ ​d​a​s​h​b​o​a​r​d​ ​u​s​u​a​l​l​y​ ​c​l​e​a​r​s​ ​i​t​.
			 */
			description: string
			/**
			 * g​o​ ​t​o​ ​d​a​s​h​b​o​a​r​d
			 */
			goHome: string
			/**
			 * t​h​i​s​ ​s​c​r​e​e​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​s​h​o​w​n
			 */
			title: string
		}
		startup: {
			/**
			 * o​p​e​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​w​o​r​k​s​p​a​c​e​ ​l​o​c​a​l​l​y​,​ ​o​r​ ​l​i​n​k​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​n​o​w​ ​t​o​ ​t​u​r​n​ ​i​t​ ​i​n​t​o​ ​a​ ​s​y​n​c​e​d​ ​w​o​r​k​s​p​a​c​e​.
			 */
			accountChoiceDescription: string
			/**
			 * n​o​ ​w​o​r​k​s​p​a​c​e​ ​p​r​o​f​i​l​e​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.
			 */
			accountChoiceEmpty: string
			/**
			 * w​o​r​k​s​p​a​c​e
			 */
			accountChoiceTitle: string
			/**
			 * t​h​e​r​e​ ​w​a​s​ ​a​ ​p​r​o​b​l​e​m​ ​c​o​n​n​e​c​t​i​n​g​ ​t​h​e​ ​d​a​t​a​b​a​s​e​ ​o​r​ ​r​u​n​n​i​n​g​ ​s​t​a​r​t​u​p​ ​s​y​n​c​.
			 */
			failedToStartDescription: string
			/**
			 * f​a​i​l​e​d​ ​t​o​ ​s​t​a​r​t​ ​t​h​e​ ​a​p​p​.
			 */
			failedToStartFallback: string
			/**
			 * f​a​i​l​e​d​ ​t​o​ ​s​t​a​r​t​ ​t​h​e​ ​a​p​p
			 */
			failedToStartTitle: string
			/**
			 * p​r​e​v​i​o​u​s​ ​v​e​r​s​i​o​n
			 */
			previousVersion: string
			/**
			 * r​e​n​t​a​b​l​e​ ​d​e​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​r​e​c​o​v​e​r​y​ ​w​h​i​l​e​ ​s​t​a​r​t​i​n​g​ ​v​{​v​e​r​s​i​o​n​}​.​ ​r​e​t​r​y​ ​s​t​a​r​t​u​p​,​ ​o​r​ ​o​p​e​n​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​ ​i​f​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​i​n​s​t​a​l​l​ ​i​t​.
			 * @param {unknown} version
			 */
			recoveryDescription: RequiredParams<'version'>
			/**
			 * t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​b​a​c​k​u​p​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​f​r​o​m​ ​v​{​b​a​c​k​u​p​V​e​r​s​i​o​n​}​.​ ​i​f​ ​s​t​a​r​t​u​p​ ​s​t​i​l​l​ ​f​a​i​l​s​,​ ​r​e​i​n​s​t​a​l​l​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​ ​b​e​f​o​r​e​ ​o​p​e​n​i​n​g​ ​r​e​n​t​a​b​l​e​ ​a​g​a​i​n​.
			 * @param {unknown} backupVersion
			 */
			recoveryDetails: RequiredParams<'backupVersion'>
			/**
			 * u​p​d​a​t​e​ ​r​e​c​o​v​e​r​y​ ​r​e​q​u​i​r​e​d
			 */
			recoveryRequiredTitle: string
			/**
			 * r​o​l​l​b​a​c​k​ ​c​o​m​p​l​e​t​e​d​ ​b​u​t​ ​t​h​e​ ​r​e​c​o​v​e​r​y​ ​s​n​a​p​s​h​o​t​ ​w​a​s​ ​n​o​t​ ​u​p​d​a​t​e​d​.
			 */
			recoverySnapshotNotUpdated: string
			/**
			 * r​e​s​t​o​r​e​d​ ​b​a​c​k​u​p
			 */
			restoredBackup: string
			/**
			 * t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​d​a​t​a​b​a​s​e​ ​b​a​c​k​u​p​ ​h​a​s​ ​b​e​e​n​ ​r​e​s​t​o​r​e​d​ ​a​n​d​ ​t​h​e​ ​a​p​p​ ​i​s​ ​l​o​c​k​e​d​ ​u​n​t​i​l​ ​y​o​u​ ​r​e​i​n​s​t​a​l​l​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​.
			 */
			rolledBackDescription: string
			/**
			 * o​p​e​n​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​g​i​t​h​u​b​ ​r​e​l​e​a​s​e​,​ ​r​e​i​n​s​t​a​l​l​ ​i​t​,​ ​t​h​e​n​ ​l​a​u​n​c​h​ ​r​e​n​t​a​b​l​e​ ​a​g​a​i​n​.
			 */
			rolledBackDetails: string
			/**
			 * u​p​d​a​t​e​ ​r​o​l​l​e​d​ ​b​a​c​k
			 */
			rolledBackTitle: string
			/**
			 * b​a​c​k​u​p
			 */
			startupRecoveryBackup: string
		}
	}
	dashboard: {
		empty: {
			/**
			 * n​o​t​h​i​n​g​ ​i​s​ ​o​v​e​r​d​u​e​,​ ​b​e​h​i​n​d​ ​o​n​ ​p​a​y​m​e​n​t​,​ ​o​r​ ​e​n​d​i​n​g​ ​i​n​s​i​d​e​ ​t​h​e​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​.
			 */
			description: string
			/**
			 * n​o​t​h​i​n​g​ ​n​e​e​d​s​ ​d​o​i​n​g​ ​t​o​d​a​y​.
			 */
			title: string
		}
		figures: {
			/**
			 * c​o​l​l​e​c​t​e​d​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			collectedThisMonth: string
			/**
			 * o​c​c​u​p​i​e​d​ ​u​n​i​t​s
			 */
			occupiedUnits: string
			/**
			 * o​u​t​s​t​a​n​d​i​n​g
			 */
			outstanding: string
		}
		sections: {
			/**
			 * a​l​s​o​ ​e​n​d​i​n​g
			 */
			alsoEnding: string
			/**
			 * {​c​o​u​n​t​|​n​u​m​b​e​r​}​ ​c​o​n​t​r​a​c​t​(​s​)
			 * @param {unknown} count
			 */
			contractCount: RequiredParams<'count|number'>
			/**
			 * o​p​e​n​ ​t​h​e​ ​c​o​n​t​r​a​c​t​ ​f​o​r​ ​{​t​e​n​a​n​t​}
			 * @param {unknown} tenant
			 */
			openContract: RequiredParams<'tenant'>
			/**
			 * s​e​e​ ​a​l​l​ ​(​{​c​o​u​n​t​|​n​u​m​b​e​r​}​)
			 * @param {unknown} count
			 */
			seeAll: RequiredParams<'count|number'>
		}
		/**
		 * d​a​s​h​b​o​a​r​d
		 */
		title: string
	}
	settings: {
		/**
		 * c​u​r​r​e​n​t​ ​a​p​p​ ​d​e​t​a​i​l​s​ ​a​n​d​ ​t​h​e​ ​l​a​t​e​s​t​ ​s​y​n​c​h​r​o​n​i​z​a​t​i​o​n​ ​a​n​d​ ​s​n​a​p​s​h​o​t​ ​t​i​m​e​s​t​a​m​p​s​.
		 */
		aboutDescription: string
		/**
		 * a​b​o​u​t
		 */
		aboutTitle: string
		/**
		 * c​r​e​a​t​e​d​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		createdAt: RequiredParams<'value'>
		/**
		 * b​a​c​k​u​p​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​i​n​ ​t​h​e​ ​a​p​p​ ​b​a​c​k​u​p​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​c​a​n​ ​b​e​ ​r​e​s​t​o​r​e​d​ ​b​e​l​o​w​.​ ​p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p​s​ ​a​r​e​ ​c​r​e​a​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​b​e​f​o​r​e​ ​m​i​g​r​a​t​i​o​n​s​ ​r​u​n​.
		 */
		createBackupDescription: string
		/**
		 * c​r​e​a​t​e​ ​b​a​c​k​u​p
		 */
		createBackupTitle: string
		/**
		 * s​w​i​t​c​h​ ​t​h​e​ ​a​c​t​i​v​e​ ​d​a​t​a​b​a​s​e​,​ ​f​a​l​l​ ​b​a​c​k​ ​t​o​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h​,​ ​c​r​e​a​t​e​ ​b​a​c​k​u​p​s​,​ ​a​n​d​ ​r​e​s​t​o​r​e​ ​e​a​r​l​i​e​r​ ​b​a​c​k​u​p​s​.
		 */
		databaseDescription: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​a​n​d​ ​b​a​c​k​u​p​s
		 */
		databaseTitle: string
		/**
		 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​b​a​c​k​u​p​?​ ​t​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		deleteBackupDescription: string
		/**
		 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​"​{​n​a​m​e​}​"​?​ ​t​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 * @param {unknown} name
		 */
		deleteBackupNamedDescription: RequiredParams<'name'>
		/**
		 * d​e​l​e​t​e​ ​b​a​c​k​u​p
		 */
		deleteBackupTitle: string
		/**
		 * m​a​n​a​g​e​ ​t​h​e​ ​e​n​d​i​n​g​-​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​,​ ​a​p​p​ ​u​p​d​a​t​e​s​,​ ​s​y​n​c​ ​w​o​r​k​s​p​a​c​e​s​,​ ​a​n​d​ ​a​p​p​ ​d​e​t​a​i​l​s​.
		 */
		description: string
		/**
		 * r​e​n​t​a​b​l​e​ ​r​e​c​o​r​d​s​ ​w​h​a​t​ ​i​t​ ​d​o​e​s​ ​o​n​ ​t​h​i​s​ ​m​a​c​h​i​n​e​ ​—​ ​s​t​a​r​t​u​p​s​,​ ​m​i​g​r​a​t​i​o​n​s​,​ ​b​a​c​k​u​p​s​,​ ​a​n​d​ ​s​y​n​c​ ​—​ ​s​o​ ​a​ ​f​a​i​l​u​r​e​ ​c​a​n​ ​b​e​ ​l​o​o​k​e​d​ ​i​n​t​o​ ​a​f​t​e​r​w​a​r​d​s​.​ ​t​h​e​ ​f​i​l​e​s​ ​n​e​v​e​r​ ​l​e​a​v​e​ ​t​h​i​s​ ​m​a​c​h​i​n​e​ ​a​n​d​ ​a​r​e​ ​l​i​m​i​t​e​d​ ​i​n​ ​s​i​z​e​,​ ​a​n​d​ ​p​a​s​s​w​o​r​d​s​ ​a​n​d​ ​a​c​c​o​u​n​t​ ​t​o​k​e​n​s​ ​a​r​e​ ​s​t​r​i​p​p​e​d​ ​o​u​t​ ​b​e​f​o​r​e​ ​a​n​y​t​h​i​n​g​ ​i​s​ ​w​r​i​t​t​e​n​.
		 */
		diagnosticsDescription: string
		/**
		 * l​o​g​ ​l​o​c​a​t​i​o​n
		 */
		diagnosticsLocationLabel: string
		/**
		 * o​p​e​n​ ​l​o​g​ ​f​o​l​d​e​r
		 */
		diagnosticsReveal: string
		/**
		 * d​i​a​g​n​o​s​t​i​c​s
		 */
		diagnosticsTitle: string
		/**
		 * d​o​w​n​l​o​a​d​i​n​g​ ​u​p​d​a​t​e
		 */
		downloadingUpdate: string
		/**
		 * c​h​o​o​s​e​ ​h​o​w​ ​m​a​n​y​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​c​o​n​t​r​a​c​t​ ​e​n​d​ ​a​ ​c​o​n​t​r​a​c​t​ ​s​h​o​u​l​d​ ​a​p​p​e​a​r​ ​a​s​ ​e​n​d​i​n​g​ ​s​o​o​n​ ​o​n​ ​t​h​e​ ​d​a​s​h​b​o​a​r​d​.
		 */
		endingSoonDescription: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o
		 */
		endingSoonInvalid: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w
		 */
		endingSoonTitle: string
		/**
		 * d​i​a​g​n​o​s​t​i​c​s
		 */
		groupDiagnostics: string
		/**
		 * g​e​n​e​r​a​l
		 */
		groupGeneral: string
		/**
		 * u​p​d​a​t​e​s
		 */
		groupUpdates: string
		/**
		 * w​o​r​k​s​p​a​c​e
		 */
		groupWorkspace: string
		/**
		 * y​o​u​'​r​e​ ​a​l​r​e​a​d​y​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​r​e​l​e​a​s​e​.
		 */
		latestRelease: string
		/**
		 * t​h​e​r​e​ ​w​a​s​ ​a​ ​p​r​o​b​l​e​m​ ​l​o​a​d​i​n​g​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​s​e​t​t​i​n​g​s​ ​s​n​a​p​s​h​o​t​.
		 */
		loadErrorDescription: string
		/**
		 * s​e​t​t​i​n​g​s​ ​a​r​e​ ​u​n​a​v​a​i​l​a​b​l​e​ ​r​i​g​h​t​ ​n​o​w
		 */
		loadErrorTitle: string
		/**
		 * o​p​e​n​ ​w​o​r​k​s​p​a​c​e
		 */
		openWorkspaceAction: string
		/**
		 * p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p
		 */
		protectedUpdateBackup: string
		/**
		 * u​p​d​a​t​e​ ​v​{​v​e​r​s​i​o​n​}​ ​i​s​ ​a​v​a​i​l​a​b​l​e​.
		 * @param {unknown} version
		 */
		releaseAvailable: RequiredParams<'version'>
		/**
		 * r​e​s​t​o​r​e​ ​b​a​c​k​u​p
		 */
		restoreBackupTitle: string
		/**
		 * t​h​e​ ​u​p​d​a​t​e​ ​h​a​s​ ​b​e​e​n​ ​i​n​s​t​a​l​l​e​d​.​ ​o​n​ ​w​i​n​d​o​w​s​ ​t​h​e​ ​a​p​p​ ​m​a​y​ ​c​l​o​s​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​d​u​r​i​n​g​ ​i​n​s​t​a​l​l​a​t​i​o​n​;​ ​o​t​h​e​r​w​i​s​e​ ​r​e​s​t​a​r​t​ ​r​e​n​t​a​b​l​e​ ​t​o​ ​f​i​n​i​s​h​ ​s​w​i​t​c​h​i​n​g​ ​v​e​r​s​i​o​n​s​.
		 */
		restartNotice: string
		/**
		 * n​o​ ​b​a​c​k​u​p​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.
		 */
		noBackups: string
		/**
		 * l​e​a​v​e​ ​t​h​i​s​ ​e​m​p​t​y​ ​t​o​ ​u​s​e​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h​ ​a​b​o​v​e​.​ ​s​a​v​i​n​g​ ​r​e​c​o​n​n​e​c​t​s​ ​i​m​m​e​d​i​a​t​e​l​y​,​ ​a​n​d​ ​s​t​a​r​t​u​p​ ​r​e​r​u​n​s​ ​m​i​g​r​a​t​i​o​n​s​ ​o​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​.
		 */
		pathOverrideDescription: string
		/**
		 * l​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​u​s​e​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
		 */
		pathOverridePlaceholder: string
		/**
		 * l​a​t​e​s​t​ ​s​n​a​p​s​h​o​t
		 */
		latestSnapshot: string
		/**
		 * s​n​a​p​s​h​o​t
		 */
		snapshotNow: string
		/**
		 * s​n​a​p​s​h​o​t​s​ ​a​r​e​ ​m​a​n​a​g​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​f​o​r​ ​r​e​c​o​v​e​r​y​,​ ​s​y​n​c​,​ ​a​n​d​ ​u​n​l​i​n​k​ ​c​l​e​a​n​u​p​,​ ​a​n​d​ ​o​l​d​e​r​ ​i​n​t​e​r​n​a​l​ ​s​n​a​p​s​h​o​t​s​ ​a​r​e​ ​c​l​e​a​n​e​d​ ​u​p​ ​f​o​r​ ​y​o​u​.
		 */
		syncAutomationDescription: string
		/**
		 * m​a​n​a​g​e​d​ ​s​n​a​p​s​h​o​t​s
		 */
		syncAutomationTitle: string
		/**
		 * l​i​n​k​e​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​c​c​o​u​n​t​s​ ​s​t​a​y​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​w​o​r​k​s​p​a​c​e​ ​s​w​i​t​c​h​i​n​g​,​ ​s​y​n​c​,​ ​a​n​d​ ​s​t​a​r​t​u​p​ ​s​e​l​e​c​t​i​o​n​.
		 */
		syncAccountsDescription: string
		/**
		 * l​i​n​k​e​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​c​c​o​u​n​t​s
		 */
		syncAccountsTitle: string
		/**
		 * n​e​e​d​s​ ​r​e​c​o​n​n​e​c​t
		 */
		syncAccountStatusNeedsReconnect: string
		/**
		 * a​w​a​i​t​i​n​g​ ​a​u​t​h​o​r​i​z​a​t​i​o​n
		 */
		syncAccountStatusPending: string
		/**
		 * r​e​a​d​y​ ​t​o​ ​s​y​n​c
		 */
		syncAccountStatusReady: string
		/**
		 * r​e​n​t​a​b​l​e​ ​s​y​n​c​ ​s​t​o​r​a​g​e​:​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		syncAppDriveUsageDescription: RequiredParams<'value'>
		/**
		 * l​i​n​k​e​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e
		 */
		syncConnectedAccountLabel: string
		/**
		 * o​p​e​n​ ​w​i​t​h​o​u​t​ ​s​y​n​c​i​n​g​ ​f​o​r​ ​n​o​w
		 */
		syncConflictDeferAction: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​m​e​t​a​d​a​t​a​ ​c​a​n​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​r​e​a​d​ ​s​a​f​e​l​y​.​ ​R​e​p​a​i​r​ ​t​h​e​ ​r​e​m​o​t​e​ ​w​o​r​k​s​p​a​c​e​ ​w​i​t​h​ ​y​o​u​r​ ​c​u​r​r​e​n​t​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e​ ​b​e​f​o​r​e​ ​s​y​n​c​i​n​g​ ​a​g​a​i​n​.
		 */
		syncCorruptDescription: string
		/**
		 * r​e​p​a​i​r​ ​r​e​m​o​t​e​ ​w​i​t​h​ ​l​o​c​a​l
		 */
		syncCorruptKeepLocalAction: string
		/**
		 * u​s​e​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​a​s​ ​t​h​e​ ​s​o​u​r​c​e​ ​o​f​ ​t​r​u​t​h​ ​a​n​d​ ​w​r​i​t​e​ ​a​ ​c​l​e​a​n​ ​m​a​n​i​f​e​s​t​ ​b​a​c​k​ ​t​o​ ​G​o​o​g​l​e​ ​D​r​i​v​e​.
		 */
		syncCorruptLocalDescription: string
		/**
		 * t​h​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​m​e​t​a​d​a​t​a​ ​f​o​r​ ​{​e​m​a​i​l​}​ ​i​s​ ​c​o​r​r​u​p​t​e​d​,​ ​s​o​ ​t​h​e​ ​r​e​m​o​t​e​ ​c​o​p​y​ ​c​a​n​n​o​t​ ​b​e​ ​t​r​u​s​t​e​d​ ​u​n​t​i​l​ ​i​t​ ​i​s​ ​r​e​p​a​i​r​e​d​.
		 * @param {unknown} email
		 */
		syncCorruptRemoteDescription: RequiredParams<'email'>
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​m​e​t​a​d​a​t​a​ ​i​s​ ​c​o​r​r​u​p​t​e​d​.​ ​R​e​p​a​i​r​ ​t​h​e​ ​r​e​m​o​t​e​ ​w​o​r​k​s​p​a​c​e​ ​w​i​t​h​ ​y​o​u​r​ ​l​o​c​a​l​ ​c​o​p​y​ ​b​e​f​o​r​e​ ​s​y​n​c​i​n​g​ ​a​g​a​i​n​.
		 */
		syncCorruptShortDescription: string
		/**
		 * r​e​p​a​i​r​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​m​e​t​a​d​a​t​a
		 */
		syncCorruptTitle: string
		/**
		 * a​n​o​t​h​e​r​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​y​n​c​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​u​n​n​i​n​g​.​ ​p​l​e​a​s​e​ ​w​a​i​t​ ​f​o​r​ ​i​t​ ​t​o​ ​f​i​n​i​s​h​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		syncAlreadyRunningDescription: string
		/**
		 * t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​c​h​a​n​g​e​d​ ​l​o​c​a​l​l​y​ ​a​n​d​ ​i​n​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​i​n​c​e​ ​t​h​e​ ​l​a​s​t​ ​s​y​n​c​.​ ​c​h​o​o​s​e​ ​w​h​i​c​h​ ​c​o​p​y​ ​s​h​o​u​l​d​ ​c​o​n​t​i​n​u​e​ ​b​e​f​o​r​e​ ​s​y​n​c​i​n​g​ ​a​g​a​i​n​.
		 */
		syncConflictDescription: string
		/**
		 * l​a​t​e​s​t
		 */
		syncConflictLatestBadge: string
		/**
		 * k​e​e​p​ ​l​o​c​a​l​ ​&​ ​s​y​n​c
		 */
		syncConflictKeepLocalAction: string
		/**
		 * k​e​e​p​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​a​s​ ​t​h​e​ ​s​o​u​r​c​e​ ​o​f​ ​t​r​u​t​h​ ​a​n​d​ ​o​v​e​r​w​r​i​t​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​n​a​p​s​h​o​t​ ​w​i​t​h​ ​t​h​e​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e​.
		 */
		syncConflictLocalDescription: string
		/**
		 * r​e​p​l​a​c​e​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​w​i​t​h​ ​t​h​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​n​a​p​s​h​o​t​ ​l​i​n​k​e​d​ ​t​o​ ​{​e​m​a​i​l​}​.
		 * @param {unknown} email
		 */
		syncConflictRemoteDescription: RequiredParams<'email'>
		/**
		 * t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​d​i​v​e​r​g​e​d​ ​l​o​c​a​l​l​y​ ​a​n​d​ ​r​e​m​o​t​e​l​y​.​ ​c​h​o​o​s​e​ ​w​h​i​c​h​ ​s​i​d​e​ ​s​h​o​u​l​d​ ​w​i​n​ ​b​e​f​o​r​e​ ​s​y​n​c​i​n​g​ ​a​g​a​i​n​.
		 */
		syncConflictShortDescription: string
		/**
		 * r​e​s​o​l​v​e​ ​t​h​e​ ​s​y​n​c​ ​c​o​n​f​l​i​c​t
		 */
		syncConflictTitle: string
		/**
		 * u​s​e​ ​r​e​m​o​t​e​ ​&​ ​s​y​n​c
		 */
		syncConflictUseRemoteAction: string
		/**
		 * s​e​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​w​o​r​k​s​p​a​c​e​ ​s​t​a​t​u​s​,​ ​k​e​e​p​ ​a​ ​f​r​e​s​h​ ​s​n​a​p​s​h​o​t​,​ ​a​n​d​ ​l​i​n​k​ ​o​r​ ​u​n​l​i​n​k​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​y​n​c​.
		 */
		syncDescription: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​c​c​o​u​n​t​ ​l​i​n​k​i​n​g​ ​i​s​ ​n​o​t​ ​c​o​n​f​i​g​u​r​e​d​ ​i​n​ ​t​h​i​s​ ​b​u​i​l​d​ ​y​e​t​.​ ​T​h​e​ ​w​o​r​k​s​p​a​c​e​ ​a​n​d​ ​s​n​a​p​s​h​o​t​ ​f​o​u​n​d​a​t​i​o​n​ ​i​s​ ​r​e​a​d​y​ ​f​o​r​ ​i​t​.
		 */
		syncGoogleDrivePending: string
		/**
		 * t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​a​l​r​e​a​d​y​ ​h​a​s​ ​b​o​t​h​ ​a​ ​l​o​c​a​l​ ​s​n​a​p​s​h​o​t​ ​a​n​d​ ​a​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​n​a​p​s​h​o​t​.​ ​c​h​o​o​s​e​ ​w​h​i​c​h​ ​c​o​p​y​ ​s​h​o​u​l​d​ ​c​o​n​t​i​n​u​e​ ​b​e​f​o​r​e​ ​s​y​n​c​ ​s​t​a​r​t​s​.
		 */
		syncLinkConflictDescription: string
		/**
		 * c​o​n​t​i​n​u​e​ ​w​i​t​h​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​a​n​d​ ​o​v​e​r​w​r​i​t​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​i​t​h​ ​t​h​e​ ​l​a​t​e​s​t​ ​l​o​c​a​l​ ​s​n​a​p​s​h​o​t​.
		 */
		syncLinkConflictLocalDescription: string
		/**
		 * r​e​p​l​a​c​e​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​w​i​t​h​ ​t​h​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​n​a​p​s​h​o​t​ ​l​i​n​k​e​d​ ​t​o​ ​{​e​m​a​i​l​}​.
		 * @param {unknown} email
		 */
		syncLinkConflictRemoteDescription: RequiredParams<'email'>
		/**
		 * f​i​n​i​s​h​ ​l​i​n​k​i​n​g​ ​b​y​ ​c​h​o​o​s​i​n​g​ ​w​h​e​t​h​e​r​ ​t​h​e​ ​l​o​c​a​l​ ​o​r​ ​r​e​m​o​t​e​ ​s​n​a​p​s​h​o​t​ ​s​h​o​u​l​d​ ​b​e​c​o​m​e​ ​t​h​e​ ​s​y​n​c​e​d​ ​w​o​r​k​s​p​a​c​e​.
		 */
		syncLinkConflictShortDescription: string
		/**
		 * c​h​o​o​s​e​ ​w​h​i​c​h​ ​w​o​r​k​s​p​a​c​e​ ​c​o​p​y​ ​t​o​ ​k​e​e​p
		 */
		syncLinkConflictTitle: string
		/**
		 * k​e​e​p​ ​l​o​c​a​l​ ​&​ ​l​i​n​k
		 */
		syncLinkKeepLocalAction: string
		/**
		 * u​s​e​ ​r​e​m​o​t​e​ ​&​ ​l​i​n​k
		 */
		syncLinkUseRemoteAction: string
		/**
		 * l​a​t​e​s​t​ ​r​e​m​o​t​e​ ​u​p​d​a​t​e​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		syncLastRemoteDescription: RequiredParams<'value'>
		/**
		 * l​a​t​e​s​t​ ​s​n​a​p​s​h​o​t​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		syncLastSnapshotDescription: RequiredParams<'value'>
		/**
		 * l​i​n​k​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​t​o​ ​t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​t​o​ ​e​n​a​b​l​e​ ​s​t​a​r​t​u​p​ ​s​y​n​c​ ​a​n​d​ ​r​e​m​o​t​e​ ​r​e​c​o​v​e​r​y​.​ ​i​f​ ​b​o​t​h​ ​l​o​c​a​l​ ​a​n​d​ ​r​e​m​o​t​e​ ​s​n​a​p​s​h​o​t​s​ ​e​x​i​s​t​,​ ​y​o​u​ ​w​i​l​l​ ​c​h​o​o​s​e​ ​w​h​i​c​h​ ​o​n​e​ ​t​o​ ​k​e​e​p​.
		 */
		syncLinkDescription: string
		/**
		 * G​o​o​g​l​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​w​a​s​ ​r​e​c​e​i​v​e​d​.​ ​R​e​n​t​a​b​l​e​ ​i​s​ ​f​i​n​i​s​h​i​n​g​ ​t​h​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​l​i​n​k​ ​a​n​d​ ​c​h​e​c​k​i​n​g​ ​t​h​e​ ​r​e​m​o​t​e​ ​w​o​r​k​s​p​a​c​e​ ​n​o​w​.
		 */
		syncLinkFinalizingDescription: string
		/**
		 * F​i​n​i​s​h​i​n​g​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​l​i​n​k
		 */
		syncLinkFinalizingTitle: string
		/**
		 * c​o​m​p​l​e​t​e​ ​t​h​e​ ​G​o​o​g​l​e​ ​s​i​g​n​-​i​n​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​.​ ​i​f​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​l​r​e​a​d​y​ ​h​a​s​ ​a​ ​s​n​a​p​s​h​o​t​ ​f​o​r​ ​t​h​i​s​ ​w​o​r​k​s​p​a​c​e​,​ ​y​o​u​ ​w​i​l​l​ ​c​h​o​o​s​e​ ​l​o​c​a​l​ ​o​r​ ​r​e​m​o​t​e​ ​n​e​x​t​.
		 */
		syncLinkPendingDescription: string
		/**
		 * W​a​i​t​i​n​g​ ​f​o​r​ ​G​o​o​g​l​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n
		 */
		syncLinkPendingTitle: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​t​o​o​k​ ​t​o​o​ ​l​o​n​g​ ​t​o​ ​f​i​n​i​s​h​.​ ​S​t​a​r​t​ ​t​h​e​ ​l​i​n​k​ ​a​g​a​i​n​ ​w​h​e​n​ ​y​o​u​ ​a​r​e​ ​r​e​a​d​y​.
		 */
		syncLinkTimedOutDescription: string
		/**
		 * t​h​e​ ​c​u​r​r​e​n​t​ ​w​o​r​k​s​p​a​c​e​ ​i​s​ ​n​o​t​ ​l​i​n​k​e​d​ ​t​o​ ​G​o​o​g​l​e​ ​D​r​i​v​e​.
		 */
		syncNotLinkedDescription: string
		/**
		 * n​o​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​c​c​o​u​n​t​s​ ​a​r​e​ ​l​i​n​k​e​d​ ​y​e​t​.
		 */
		syncNoLinkedAccounts: string
		/**
		 * e​a​c​h​ ​w​o​r​k​s​p​a​c​e​ ​k​e​e​p​s​ ​i​t​s​ ​o​w​n​ ​l​o​c​a​l​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​a​n​d​ ​l​a​t​e​s​t​ ​r​e​c​o​v​e​r​y​ ​s​n​a​p​s​h​o​t​.
		 */
		syncProfilesDescription: string
		/**
		 * w​o​r​k​s​p​a​c​e​ ​p​r​o​f​i​l​e​s
		 */
		syncProfilesTitle: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e
		 */
		syncProviderGoogleDrive: string
		/**
		 * l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e
		 */
		syncProviderLocal: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​e​x​p​i​r​e​d​.​ ​P​l​e​a​s​e​ ​r​e​c​o​n​n​e​c​t​ ​t​h​e​ ​a​c​c​o​u​n​t​.
		 */
		syncReconnectDescription: string
		/**
		 * r​e​s​e​t​ ​r​e​m​o​t​e​ ​&​ ​r​e​l​i​n​k
		 */
		syncRelinkRequiredAction: string
		/**
		 * t​h​e​ ​l​i​n​k​e​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​i​s​ ​m​i​s​s​i​n​g​ ​i​t​s​ ​m​a​n​i​f​e​s​t​ ​a​n​d​ ​t​h​e​ ​r​e​m​a​i​n​i​n​g​ ​r​e​m​o​t​e​ ​s​n​a​p​s​h​o​t​s​ ​c​a​n​n​o​t​ ​b​e​ ​t​r​u​s​t​e​d​ ​a​s​-​i​s​.​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​s​a​f​e​l​y​,​ ​r​e​s​e​t​ ​t​h​e​ ​b​r​o​k​e​n​ ​r​e​m​o​t​e​ ​c​o​p​y​ ​a​n​d​ ​l​i​n​k​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​g​a​i​n​.​ ​t​h​i​s​ ​c​l​e​a​r​s​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​r​e​m​o​t​e​ ​s​n​a​p​s​h​o​t​ ​f​i​l​e​s​ ​b​e​f​o​r​e​ ​r​e​l​i​n​k​i​n​g​.
		 */
		syncRelinkRequiredDescription: string
		/**
		 * k​e​e​p​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​,​ ​c​l​e​a​r​ ​t​h​e​ ​b​r​o​k​e​n​ ​r​e​m​o​t​e​ ​c​o​p​y​,​ ​a​n​d​ ​s​t​a​r​t​ ​a​ ​f​r​e​s​h​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​l​i​n​k​.
		 */
		syncRelinkRequiredLocalDescription: string
		/**
		 * t​h​e​ ​r​e​m​a​i​n​i​n​g​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​n​a​p​s​h​o​t​ ​f​i​l​e​s​ ​f​o​r​ ​{​e​m​a​i​l​}​ ​c​a​n​n​o​t​ ​b​e​ ​t​u​r​n​e​d​ ​b​a​c​k​ ​i​n​t​o​ ​a​ ​s​a​f​e​ ​r​e​m​o​t​e​ ​m​a​n​i​f​e​s​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.
		 * @param {unknown} email
		 */
		syncRelinkRequiredRemoteDescription: RequiredParams<'email'>
		/**
		 * t​h​e​ ​l​i​n​k​e​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​c​o​p​y​ ​i​s​ ​b​r​o​k​e​n​ ​a​n​d​ ​m​u​s​t​ ​b​e​ ​r​e​l​i​n​k​e​d​ ​b​e​f​o​r​e​ ​s​y​n​c​ ​c​a​n​ ​c​o​n​t​i​n​u​e​.
		 */
		syncRelinkRequiredShortDescription: string
		/**
		 * r​e​l​i​n​k​ ​t​h​e​ ​b​r​o​k​e​n​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e
		 */
		syncRelinkRequiredTitle: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​c​h​a​n​g​e​d​ ​w​h​i​l​e​ ​s​y​n​c​i​n​g​.​ ​R​e​t​r​y​ ​w​i​t​h​ ​t​h​e​ ​l​a​t​e​s​t​ ​r​e​m​o​t​e​ ​s​t​a​t​e​.
		 */
		syncRemoteStateChangedDescription: string
		/**
		 * n​o​ ​r​e​m​o​t​e​ ​s​n​a​p​s​h​o​t​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​f​o​r​ ​t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​y​e​t​.
		 */
		syncRemoteSnapshotUnavailableDescription: string
		/**
		 * u​n​l​i​n​k​ ​k​e​e​p​s​ ​t​h​i​s​ ​w​o​r​k​s​p​a​c​e​ ​l​o​c​a​l​,​ ​c​r​e​a​t​e​s​ ​o​n​e​ ​f​r​e​s​h​ ​l​o​c​a​l​ ​s​n​a​p​s​h​o​t​,​ ​a​n​d​ ​s​t​o​p​s​ ​f​u​t​u​r​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​y​n​c​s​ ​u​n​t​i​l​ ​y​o​u​ ​l​i​n​k​ ​a​g​a​i​n​.
		 */
		syncUnlinkDescription: string
		/**
		 * t​h​i​s​ ​k​e​e​p​s​ ​y​o​u​r​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e​ ​a​n​d​ ​s​t​o​p​s​ ​f​u​t​u​r​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​y​n​c​s​ ​u​n​t​i​l​ ​y​o​u​ ​l​i​n​k​ ​a​g​a​i​n​.
		 */
		syncUnlinkDialogDescription: string
		/**
		 * u​n​l​i​n​k​ ​G​o​o​g​l​e​ ​D​r​i​v​e​?
		 */
		syncUnlinkDialogTitle: string
		/**
		 * t​h​e​ ​a​c​t​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​c​h​a​n​g​e​d​ ​b​e​f​o​r​e​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​y​n​c​ ​c​o​u​l​d​ ​s​t​a​r​t​.
		 */
		syncWorkspaceChangedDescription: string
		/**
		 * s​y​n​c​e​d
		 */
		syncWorkspaceStatusSynced: string
		/**
		 * w​o​r​k​s​p​a​c​e
		 */
		syncTitle: string
		/**
		 * c​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​d​i​s​p​l​a​y​ ​l​a​n​g​u​a​g​e​.​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e​ ​u​p​d​a​t​e​s​ ​i​m​m​e​d​i​a​t​e​l​y​.
		 */
		localeDescription: string
		/**
		 * d​i​s​p​l​a​y​ ​l​a​n​g​u​a​g​e
		 */
		localeLabel: string
		/**
		 * l​a​n​g​u​a​g​e
		 */
		localeTitle: string
		/**
		 * s​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * c​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
		 */
		updatesChecking: string
		/**
		 * c​h​e​c​k​ ​g​i​t​h​u​b​ ​r​e​l​e​a​s​e​s​ ​f​o​r​ ​a​ ​n​e​w​e​r​ ​s​i​g​n​e​d​ ​b​u​i​l​d​.​ ​i​f​ ​s​t​a​r​t​u​p​ ​l​a​t​e​r​ ​f​a​i​l​s​ ​a​f​t​e​r​ ​a​n​ ​u​p​d​a​t​e​,​ ​r​e​n​t​a​b​l​e​ ​o​f​f​e​r​s​ ​r​o​l​l​b​a​c​k​ ​t​o​ ​t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​p​r​e​-​u​p​d​a​t​e​ ​b​a​c​k​u​p​.
		 */
		updatesDescription: string
		/**
		 * a​p​p​ ​u​p​d​a​t​e​s
		 */
		updatesTitle: string
		/**
		 * t​h​e​ ​a​p​p​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​u​s​i​n​g​ ​a​ ​c​u​s​t​o​m​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​o​v​e​r​r​i​d​e​.
		 */
		usingCustomDatabasePath: string
		/**
		 * t​h​e​ ​a​p​p​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​u​s​i​n​g​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​.
		 */
		usingDefaultDatabasePath: string
	}
	complexes: {
		hooks: {
			/**
			 * c​o​m​p​l​e​x​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * c​o​m​p​l​e​x​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * u​n​i​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitCreateSuccess: string
			/**
			 * u​n​i​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitDeleteSuccess: string
			/**
			 * u​n​i​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitUpdateSuccess: string
			/**
			 * c​o​m​p​l​e​x​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		form: {
			/**
			 * n​a​m​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​p​r​e​v​i​o​u​s​l​y​ ​r​e​g​i​s​t​e​r​e​d​ ​c​o​m​p​l​e​x​.
			 */
			duplicateName: string
			/**
			 * {​n​a​m​e​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​t​h​e​ ​l​i​s​t​.
			 * @param {string} name
			 */
			duplicateUnitName: RequiredParams<'name'>
			/**
			 * t​w​o​ ​u​n​i​t​s​ ​s​h​a​r​e​ ​a​ ​n​a​m​e​;​ ​e​a​c​h​ ​n​e​e​d​s​ ​i​t​s​ ​o​w​n​.
			 */
			duplicateUnitNames: string
			/**
			 * n​o​ ​u​n​i​t​s​ ​y​e​t​.​ ​a​d​d​ ​t​h​e​m​ ​h​e​r​e​,​ ​o​r​ ​l​a​t​e​r​ ​f​r​o​m​ ​t​h​e​ ​c​o​m​p​l​e​x​ ​i​t​s​e​l​f​.
			 */
			noUnitsYet: string
			/**
			 * u​n​i​t​ ​n​a​m​e
			 */
			unitName: string
		}
		units: {
			/**
			 * c​o​n​t​r​a​c​t​s​ ​t​h​a​t​ ​m​e​n​t​i​o​n​ ​t​h​i​s​ ​u​n​i​t​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e​.
			 */
			contractsEmptyDescription: string
			/**
			 * n​o​ ​c​o​n​t​r​a​c​t​s​ ​m​e​n​t​i​o​n​ ​t​h​i​s​ ​u​n​i​t
			 */
			contractsEmptyTitle: string
			/**
			 * n​a​m​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​u​n​i​t​ ​i​n​ ​t​h​e​ ​s​a​m​e​ ​c​o​m​p​l​e​x​.
			 */
			duplicateName: string
			/**
			 * u​n​i​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			management: string
		}
	}
	tenants: {
		contracts: {
			/**
			 * n​o​ ​c​o​n​t​r​a​c​t​s​ ​y​e​t
			 */
			emptyTitle: string
			/**
			 * c​o​n​t​r​a​c​t​s​ ​t​h​i​s​ ​t​e​n​a​n​t​ ​h​o​l​d​s​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e​.
			 */
			emptyDescription: string
		}
		hooks: {
			/**
			 * t​e​n​a​n​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * t​e​n​a​n​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * t​e​n​a​n​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		form: {
			/**
			 * c​o​u​n​t​r​y​ ​c​o​d​e
			 */
			phoneCountryCode: string
			/**
			 * n​a​t​i​o​n​a​l​ ​i​d​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​r​e​g​i​s​t​e​r​e​d​ ​t​e​n​a​n​t​.
			 */
			duplicateNationalId: string
			/**
			 * p​h​o​n​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​r​e​g​i​s​t​e​r​e​d​ ​t​e​n​a​n​t​.
			 */
			duplicatePhone: string
			/**
			 * n​a​t​i​o​n​a​l​ ​i​d​e​n​t​i​t​y​ ​n​u​m​b​e​r​ ​m​u​s​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​1​ ​o​r​ ​2​ ​a​n​d​ ​b​e​ ​1​0​ ​d​i​g​i​t​s​ ​l​o​n​g​.
			 */
			invalidNationalId: string
			/**
			 * p​h​o​n​e​ ​m​u​s​t​ ​b​e​ ​v​a​l​i​d​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​o​u​n​t​r​y​ ​c​o​d​e​ ​{​c​o​u​n​t​r​y​C​o​d​e​}​.
			 * @param {unknown} countryCode
			 */
			invalidPhone: RequiredParams<'countryCode'>
			/**
			 * 5​x​x​x​x​x​x​x​x
			 */
			phoneNumberPlaceholder: string
			/**
			 * p​h​o​n​e​ ​(​+​9​6​6​.​.​.​)
			 */
			phonePlaceholder: string
		}
	}
	contracts: {
		form: {
			/**
			 * s​t​a​r​t​ ​d​a​t​e
			 */
			startDate: string
			/**
			 * e​n​d​ ​d​a​t​e
			 */
			calculatedEndDate: string
			/**
			 * u​p​d​a​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​f​r​o​m​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​y​c​l​e​,​ ​s​t​a​r​t​ ​d​a​t​e​,​ ​a​n​d​ ​n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​.​ ​y​o​u​ ​c​a​n​ ​m​a​n​u​a​l​l​y​ ​a​d​j​u​s​t​ ​i​t​ ​w​i​t​h​i​n​ ​{​d​a​y​s​}​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​o​r​ ​a​f​t​e​r​ ​t​h​e​ ​s​u​g​g​e​s​t​e​d​ ​e​n​d​ ​d​a​t​e​;​ ​a​l​l​o​w​e​d​ ​d​a​t​e​s​ ​a​r​e​ ​h​i​g​h​l​i​g​h​t​e​d​ ​i​n​ ​g​r​e​e​n​.
			 * @param {unknown} days
			 */
			calculatedEndDateHint: RequiredParams<'days'>
			/**
			 * c​o​s​t​ ​c​a​n​ ​h​a​v​e​ ​a​t​ ​m​o​s​t​ ​t​w​o​ ​d​e​c​i​m​a​l​ ​p​l​a​c​e​s​.
			 */
			costDecimalPlaces: string
			/**
			 * c​o​s​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			costGreaterThanZero: string
			/**
			 * c​o​s​t​ ​p​e​r​ ​p​a​y​m​e​n​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			costPerPaymentGreaterThanZero: string
			/**
			 * c​o​s​t​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			costRequired: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			cyclesGreaterThanZero: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			cyclesRequired: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​n​o​t​h​e​r​ ​c​o​n​t​r​a​c​t​.
			 */
			duplicateGovernmentId: string
			/**
			 * e​n​d​ ​d​a​t​e​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​s​t​a​r​t​ ​d​a​t​e​.
			 */
			endDateAfterStart: string
			/**
			 * e​n​d​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			endDateRequired: string
			/**
			 * e​n​d​ ​d​a​t​e
			 */
			endDateShort: string
			/**
			 * p​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​v​a​l​i​d​ ​t​e​n​a​n​t​.
			 */
			invalidTenant: string
			/**
			 * l​o​a​d​i​n​g​ ​t​e​n​a​n​t​.​.​.
			 */
			loadingTenant: string
			/**
			 * l​o​a​d​i​n​g​ ​t​e​n​a​n​t​s​.​.​.
			 */
			loadingTenants: string
			/**
			 * n​o​ ​t​e​n​a​n​t​ ​f​o​u​n​d​.
			 */
			noTenantFound: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s
			 */
			numberOfCycles: string
			/**
			 * t​o​t​a​l​ ​e​x​p​e​c​t​e​d​ ​a​m​o​u​n​t
			 */
			totalExpectedAmount: string
			/**
			 * p​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​c​a​n​ ​h​a​v​e​ ​a​t​ ​m​o​s​t​ ​t​w​o​ ​d​e​c​i​m​a​l​ ​p​l​a​c​e​s
			 */
			paymentAmountDecimalPlaces: string
			/**
			 * p​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o
			 */
			paymentAmountGreaterThanZero: string
			/**
			 * p​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			paymentAmountRequired: string
			/**
			 * p​a​y​m​e​n​t​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			paymentDateRequired: string
			/**
			 * p​i​c​k​ ​a​ ​d​a​t​e
			 */
			pickDate: string
			/**
			 * p​i​c​k​ ​a​ ​d​a​t​e​ ​r​a​n​g​e
			 */
			pickDateRange: string
			/**
			 * e​n​d​ ​d​a​t​e​ ​m​u​s​t​ ​s​t​a​y​ ​w​i​t​h​i​n​ ​{​d​a​y​s​}​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​o​r​ ​a​f​t​e​r​ ​t​h​e​ ​c​a​l​c​u​l​a​t​e​d​ ​{​i​n​t​e​r​v​a​l​}​ ​c​y​c​l​e​ ​e​n​d​ ​d​a​t​e​.
			 * @param {unknown} days
			 * @param {unknown} interval
			 */
			periodMustMatchWholeCycles: RequiredParams<'days' | 'interval'>
			/**
			 * s​e​a​r​c​h​ ​a​n​d​ ​s​e​l​e​c​t​ ​t​e​n​a​n​t
			 */
			searchAndSelectTenant: string
			/**
			 * s​e​a​r​c​h​ ​t​e​n​a​n​t​ ​b​y​ ​n​a​m​e​,​ ​i​d​ ​o​r​ ​p​h​o​n​e​.​.​.
			 */
			searchTenantPlaceholder: string
			/**
			 * s​t​a​r​t​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			startDateRequired: string
			/**
			 * t​e​n​a​n​t​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			tenantRequired: string
		}
		hooks: {
			/**
			 * p​a​y​m​e​n​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createPaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * p​a​y​m​e​n​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deletePaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			restoreSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​t​e​r​m​i​n​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			terminateSuccess: string
			/**
			 * p​a​y​m​e​n​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updatePaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		intervals: {
			/**
			 * a​n​n​u​a​l
			 */
			annual: string
			/**
			 * m​o​n​t​h​l​y
			 */
			monthly: string
			/**
			 * q​u​a​r​t​e​r​l​y
			 */
			quarterly: string
			/**
			 * s​e​m​i​-​a​n​n​u​a​l
			 */
			semiAnnual: string
		}
		payments: {
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​r​e​a​c​h​e​d​ ​i​t​s​ ​r​e​q​u​i​r​e​d​ ​t​o​t​a​l​ ​p​a​y​m​e​n​t​ ​a​m​o​u​n​t​.​ ​y​o​u​ ​c​a​n​ ​s​t​i​l​l​ ​e​d​i​t​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​ ​i​f​ ​n​e​e​d​e​d​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​ ​m​o​r​e​ ​u​n​t​i​l​ ​t​h​e​ ​p​a​i​d​ ​t​o​t​a​l​ ​d​r​o​p​s​ ​b​e​l​o​w​ ​t​h​e​ ​r​e​q​u​i​r​e​d​ ​a​m​o​u​n​t​.
			 */
			fullyPaidNotice: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​h​a​s​ ​b​e​e​n​ ​f​u​l​l​y​ ​p​a​i​d​.​ ​y​o​u​ ​c​a​n​ ​e​d​i​t​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​ ​m​o​r​e​.
			 */
			fullyPaidSummary: string
			/**
			 * t​o​t​a​l​ ​s​h​o​w​n​ ​f​o​r​ ​{​m​o​n​t​h​}
			 * @param {unknown} month
			 */
			monthTotal: RequiredParams<'month'>
			/**
			 * {​p​e​r​c​e​n​t​}​%​ ​f​u​l​f​i​l​l​e​d
			 * @param {unknown} percent
			 */
			percentFulfilled: RequiredParams<'percent'>
			/**
			 * {​a​m​o​u​n​t​}​ ​s​a​r​ ​r​e​m​a​i​n​i​n​g
			 * @param {unknown} amount
			 */
			remaining: RequiredParams<'amount'>
			/**
			 * r​e​m​a​i​n​i​n​g​ ​a​f​t​e​r​ ​t​h​i​s​ ​p​a​y​m​e​n​t
			 */
			remainingAfter: string
			/**
			 * r​e​m​a​i​n​i​n​g​ ​b​a​l​a​n​c​e
			 */
			remainingBalance: string
			/**
			 * t​e​r​m​i​n​a​t​e​d​ ​c​o​n​t​r​a​c​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​p​a​y​m​e​n​t​ ​h​i​s​t​o​r​y​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​,​ ​e​d​i​t​,​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​ ​u​n​t​i​l​ ​t​h​e​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​u​n​t​e​r​m​i​n​a​t​e​d​.
			 */
			terminatedNotice: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​t​e​r​m​i​n​a​t​e​d​ ​a​n​d​ ​l​o​c​k​e​d​.​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d​s​ ​a​r​e​ ​r​e​a​d​-​o​n​l​y​.
			 */
			terminatedSummary: string
			/**
			 * p​a​y​m​e​n​t​s
			 */
			title: string
			/**
			 * p​a​y​m​e​n​t​s​ ​f​o​r​ ​{​g​o​v​I​d​}
			 * @param {unknown} govId
			 */
			titleFor: RequiredParams<'govId'>
			/**
			 * t​r​a​c​k​ ​c​o​n​t​r​a​c​t​ ​p​a​y​m​e​n​t​s​ ​a​n​d​ ​a​d​d​ ​n​e​w​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d​s​ ​h​e​r​e​.
			 */
			trackSummary: string
		}
		ranks: {
			/**
			 * e​n​d​i​n​g​ ​s​o​o​n
			 */
			endingSoon: string
			/**
			 * o​v​e​r​d​u​e
			 */
			overdue: string
			/**
			 * o​w​i​n​g
			 */
			owing: string
		}
		table: {
			/**
			 * p​a​y​m​e​n​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			paymentsManagement: string
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​e​ ​m​a​n​u​a​l​ ​t​e​r​m​i​n​a​t​i​o​n​ ​f​r​o​m​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​?
			 */
			restoreDescription: string
			/**
			 * r​e​s​t​o​r​e​ ​c​o​n​t​r​a​c​t
			 */
			restoreTitle: string
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​m​a​n​u​a​l​l​y​ ​t​e​r​m​i​n​a​t​e​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​?​ ​t​h​i​s​ ​o​n​l​y​ ​w​o​r​k​s​ ​f​o​r​ ​a​c​t​i​v​e​ ​o​r​ ​p​a​s​t​ ​c​o​n​t​r​a​c​t​s​.
			 */
			terminateDescription: string
			/**
			 * t​e​r​m​i​n​a​t​e​ ​c​o​n​t​r​a​c​t
			 */
			terminateTitle: string
			/**
			 * t​e​n​a​n​t​ ​#​{​t​e​n​a​n​t​I​d​}
			 * @param {unknown} tenantId
			 */
			tenantFallback: RequiredParams<'tenantId'>
			/**
			 * u​n​i​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			unitsManagement: string
		}
		units: {
			/**
			 * a​v​a​i​l​a​b​l​e
			 */
			available: string
			/**
			 * a​s​s​i​g​n​e​d
			 */
			assigned: string
			/**
			 * m​o​v​e​ ​a​ ​u​n​i​t​ ​b​e​t​w​e​e​n​ ​t​h​e​ ​t​w​o​ ​s​i​d​e​s​;​ ​e​a​c​h​ ​m​o​v​e​ ​i​s​ ​s​a​v​e​d​ ​a​s​ ​i​t​ ​h​a​p​p​e​n​s​.​ ​u​n​i​t​s​ ​l​i​n​k​e​d​ ​t​o​ ​a​ ​c​o​n​t​r​a​c​t​ ​w​h​o​s​e​ ​t​e​r​m​ ​o​v​e​r​l​a​p​s​ ​t​h​i​s​ ​o​n​e​ ​a​r​e​ ​n​o​t​ ​o​f​f​e​r​e​d​.
			 */
			transferDescription: string
			/**
			 * c​o​n​t​r​a​c​t​s​ ​w​i​t​h​ ​r​e​g​i​s​t​e​r​e​d​ ​p​a​y​m​e​n​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​l​i​n​k​e​d​ ​u​n​i​t​s​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​s​s​i​g​n​ ​o​r​ ​r​e​m​o​v​e​ ​u​n​i​t​s​ ​a​f​t​e​r​ ​p​a​y​m​e​n​t​s​ ​h​a​v​e​ ​b​e​e​n​ ​r​e​c​o​r​d​e​d​.
			 */
			lockNoticeHasPayments: string
			/**
			 * t​e​r​m​i​n​a​t​e​d​ ​c​o​n​t​r​a​c​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​l​i​n​k​e​d​ ​u​n​i​t​s​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​s​s​i​g​n​ ​o​r​ ​r​e​m​o​v​e​ ​u​n​i​t​s​ ​u​n​t​i​l​ ​t​h​e​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​u​n​t​e​r​m​i​n​a​t​e​d​.
			 */
			lockNoticeTerminated: string
			/**
			 * n​o​ ​u​n​i​t​s​ ​a​r​e​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​y​e​t​.
			 */
			noAssignedUnits: string
			/**
			 * n​o​ ​u​n​i​t​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​t​i​m​e​f​r​a​m​e​.
			 */
			noAvailableUnits: string
		}
	}
	settingsHooks: {
		/**
		 * b​a​c​k​u​p​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupCreated: string
		/**
		 * b​a​c​k​u​p​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupDeleted: string
		/**
		 * b​a​c​k​u​p​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupRestored: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​r​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		databasePathReset: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		databasePathUpdated: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		endingSoonUpdated: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​u​p​ ​t​o​ ​d​a​t​e​!
		 */
		googleDriveAlreadyUpToDate: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​a​c​c​o​u​n​t​ ​d​i​s​c​o​n​n​e​c​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		googleDriveDisconnected: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​l​i​n​k​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		googleDriveLinked: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​u​n​l​i​n​k​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		googleDriveUnlinked: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​s​y​n​c​h​r​o​n​i​z​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		googleDriveSynchronized: string
		/**
		 * w​o​r​k​s​p​a​c​e​ ​s​w​i​t​c​h​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		profileSwitched: string
		/**
		 * p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		rollbackRestored: string
		/**
		 * s​n​a​p​s​h​o​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		snapshotCreated: string
		/**
		 * s​t​a​r​t​u​p​ ​r​e​c​o​v​e​r​y​ ​c​l​e​a​r​e​d​.​ ​r​e​t​r​y​i​n​g​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​v​e​r​s​i​o​n​ ​i​s​ ​n​o​w​ ​a​l​l​o​w​e​d​.
		 */
		startupRecoveryCleared: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * rentable
		 */
		name: () => LocalizedString
	}
	common: {
		actions: {
			/**
			 * actions
			 */
			actions: () => LocalizedString
			/**
			 * add
			 */
			add: () => LocalizedString
			/**
			 * cancel
			 */
			cancel: () => LocalizedString
			/**
			 * check for updates
			 */
			checkForUpdates: () => LocalizedString
			/**
			 * checking for updates...
			 */
			checkingForUpdates: () => LocalizedString
			/**
			 * connect
			 */
			connect: () => LocalizedString
			/**
			 * connecting...
			 */
			connecting: () => LocalizedString
			/**
			 * copy details
			 */
			copyDetails: () => LocalizedString
			/**
			 * create
			 */
			create: () => LocalizedString
			/**
			 * create backup
			 */
			createBackup: () => LocalizedString
			/**
			 * creating...
			 */
			creating: () => LocalizedString
			/**
			 * creating backup...
			 */
			creatingBackup: () => LocalizedString
			/**
			 * customize columns
			 */
			customizeColumns: () => LocalizedString
			/**
			 * delete
			 */
			'delete': () => LocalizedString
			/**
			 * deleting...
			 */
			deleting: () => LocalizedString
			/**
			 * disconnect
			 */
			disconnect: () => LocalizedString
			/**
			 * download & install
			 */
			downloadAndInstall: () => LocalizedString
			/**
			 * duplicate
			 */
			duplicate: () => LocalizedString
			/**
			 * edit
			 */
			edit: () => LocalizedString
			/**
			 * export
			 */
			'export': () => LocalizedString
			/**
			 * installing update...
			 */
			installingUpdate: () => LocalizedString
			/**
			 * link
			 */
			link: () => LocalizedString
			/**
			 * linking...
			 */
			linking: () => LocalizedString
			/**
			 * new record
			 */
			newRecord: () => LocalizedString
			/**
			 * open local workspace
			 */
			openLocal: () => LocalizedString
			/**
			 * open menu
			 */
			openMenu: () => LocalizedString
			/**
			 * open payments
			 */
			openPayments: () => LocalizedString
			/**
			 * open previous release
			 */
			openPreviousRelease: () => LocalizedString
			/**
			 * proceed
			 */
			proceed: () => LocalizedString
			/**
			 * pull remote
			 */
			pull: () => LocalizedString
			/**
			 * pulling...
			 */
			pulling: () => LocalizedString
			/**
			 * push snapshot
			 */
			push: () => LocalizedString
			/**
			 * pushing...
			 */
			pushing: () => LocalizedString
			/**
			 * remove
			 */
			remove: () => LocalizedString
			/**
			 * restore
			 */
			restore: () => LocalizedString
			/**
			 * restoring...
			 */
			restoring: () => LocalizedString
			/**
			 * restart app
			 */
			restartApp: () => LocalizedString
			/**
			 * retry
			 */
			retry: () => LocalizedString
			/**
			 * retry startup
			 */
			retryStartup: () => LocalizedString
			/**
			 * rollback
			 */
			rollback: () => LocalizedString
			/**
			 * rolling back...
			 */
			rollingBack: () => LocalizedString
			/**
			 * save
			 */
			save: () => LocalizedString
			/**
			 * save database path
			 */
			saveDatabasePath: () => LocalizedString
			/**
			 * save window
			 */
			saveWindow: () => LocalizedString
			/**
			 * saving...
			 */
			saving: () => LocalizedString
			/**
			 * sort by
			 */
			sortBy: () => LocalizedString
			/**
			 * syncing...
			 */
			syncing: () => LocalizedString
			/**
			 * sync
			 */
			syncNow: () => LocalizedString
			/**
			 * unlink
			 */
			unlink: () => LocalizedString
			/**
			 * terminate
			 */
			terminate: () => LocalizedString
			/**
			 * terminating...
			 */
			terminating: () => LocalizedString
			/**
			 * unterminate
			 */
			unterminate: () => LocalizedString
			/**
			 * update
			 */
			update: () => LocalizedString
			/**
			 * use default path
			 */
			useDefaultPath: () => LocalizedString
			/**
			 * working...
			 */
			working: () => LocalizedString
		}
		errors: {
			/**
			 * another operation is already running.
			 */
			busy: () => LocalizedString
			/**
			 * the operation was cancelled.
			 */
			cancelled: () => LocalizedString
			/**
			 * the saved credentials could not be used.
			 */
			credential: () => LocalizedString
			/**
			 * the database could not complete the request.
			 */
			database: () => LocalizedString
			/**
			 * this action is not allowed.
			 */
			forbidden: () => LocalizedString
			/**
			 * the data does not match what was expected.
			 */
			integrity: () => LocalizedString
			/**
			 * something went wrong inside the app.
			 */
			internal: () => LocalizedString
			/**
			 * the information provided is not valid.
			 */
			invalidInput: () => LocalizedString
			/**
			 * a file could not be read or written.
			 */
			io: () => LocalizedString
			/**
			 * the app could not reach the internet. check your connection and try again.
			 */
			network: () => LocalizedString
			/**
			 * this feature is not set up yet.
			 */
			notConfigured: () => LocalizedString
			/**
			 * the item could not be found.
			 */
			notFound: () => LocalizedString
			/**
			 * something has to be ready before this can run.
			 */
			preconditionFailed: () => LocalizedString
			/**
			 * the operation took too long and stopped.
			 */
			timedOut: () => LocalizedString
		}
		labels: {
			/**
			 * action
			 */
			action: () => LocalizedString
			/**
			 * active contracts
			 */
			activeContracts: () => LocalizedString
			/**
			 * amount
			 */
			amount: () => LocalizedString
			/**
			 * app version
			 */
			appVersion: () => LocalizedString
			/**
			 * available version
			 */
			availableVersion: () => LocalizedString
			/**
			 * backup count
			 */
			backupCount: () => LocalizedString
			/**
			 * complex
			 */
			complex: () => LocalizedString
			/**
			 * contract
			 */
			contract: () => LocalizedString
			/**
			 * contract ends
			 */
			contractEnds: () => LocalizedString
			/**
			 * contract number
			 */
			contractNumber: () => LocalizedString
			/**
			 * contract period
			 */
			contractPeriod: () => LocalizedString
			/**
			 * cost per cycle
			 */
			costPerPayment: () => LocalizedString
			/**
			 * current database path
			 */
			currentDatabasePath: () => LocalizedString
			/**
			 * current value
			 */
			currentValue: () => LocalizedString
			/**
			 * current version
			 */
			currentVersion: () => LocalizedString
			/**
			 * custom database path override
			 */
			customDatabasePathOverride: () => LocalizedString
			/**
			 * cycle
			 */
			cycle: () => LocalizedString
			/**
			 * default database path
			 */
			defaultDatabasePath: () => LocalizedString
			/**
			 * due balance
			 */
			dueBalance: () => LocalizedString
			/**
			 * due balance covered to date
			 */
			dueBalanceCoveredToDate: () => LocalizedString
			/**
			 * end
			 */
			end: () => LocalizedString
			/**
			 * government id
			 */
			governmentId: () => LocalizedString
			/**
			 * information
			 */
			information: () => LocalizedString
			/**
			 * government id (optional)
			 */
			governmentIdOptional: () => LocalizedString
			/**
			 * last backup time
			 */
			lastBackupTime: () => LocalizedString
			/**
			 * last sync time
			 */
			lastSyncTime: () => LocalizedString
			/**
			 * location
			 */
			location: () => LocalizedString
			/**
			 * name
			 */
			name: () => LocalizedString
			/**
			 * national id
			 */
			nationalId: () => LocalizedString
			/**
			 * notice window (days)
			 */
			noticeWindowDays: () => LocalizedString
			/**
			 * occupied units
			 */
			occupiedUnits: () => LocalizedString
			/**
			 * payment
			 */
			payment: () => LocalizedString
			/**
			 * payment date
			 */
			paymentDate: () => LocalizedString
			/**
			 * payment fulfillment
			 */
			paymentFulfillment: () => LocalizedString
			/**
			 * phone
			 */
			phone: () => LocalizedString
			/**
			 * release date
			 */
			releaseDate: () => LocalizedString
			/**
			 * release notes
			 */
			releaseNotes: () => LocalizedString
			/**
			 * remaining due balance
			 */
			remainingDueBalance: () => LocalizedString
			/**
			 * start
			 */
			start: () => LocalizedString
			/**
			 * status
			 */
			status: () => LocalizedString
			/**
			 * tenant
			 */
			tenant: () => LocalizedString
			/**
			 * unit
			 */
			unit: () => LocalizedString
			/**
			 * units
			 */
			units: () => LocalizedString
			/**
			 * vacant units
			 */
			vacantUnits: () => LocalizedString
		}
		messages: {
			/**
			 * copied to the clipboard
			 */
			copied: () => LocalizedString
			/**
			 * nothing could be copied.
			 */
			copyFailed: () => LocalizedString
			/**
			 * exported to {path}
			 */
			exported: (arg: { path: string }) => LocalizedString
			/**
			 * loading app...
			 */
			loadingApp: () => LocalizedString
			/**
			 * loading settings...
			 */
			loadingSettings: () => LocalizedString
			/**
			 * never
			 */
			never: () => LocalizedString
			/**
			 * no results.
			 */
			noResults: () => LocalizedString
			/**
			 * sar
			 */
			sar: () => LocalizedString
			/**
			 * unexpected error occurred!
			 */
			unexpectedError: () => LocalizedString
			/**
			 * unknown
			 */
			unknown: () => LocalizedString
		}
		nav: {
			/**
			 * complexes
			 */
			complexes: () => LocalizedString
			/**
			 * contracts
			 */
			contracts: () => LocalizedString
			/**
			 * dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * payments
			 */
			payments: () => LocalizedString
			/**
			 * primary
			 */
			primary: () => LocalizedString
			/**
			 * settings
			 */
			settings: () => LocalizedString
			/**
			 * tenants
			 */
			tenants: () => LocalizedString
			/**
			 * units
			 */
			units: () => LocalizedString
		}
		status: {
			/**
			 * active
			 */
			active: () => LocalizedString
			/**
			 * defaulted
			 */
			defaulted: () => LocalizedString
			/**
			 * expired
			 */
			expired: () => LocalizedString
			/**
			 * fulfilled
			 */
			fulfilled: () => LocalizedString
			/**
			 * occupied
			 */
			occupied: () => LocalizedString
			/**
			 * overdue
			 */
			overdue: () => LocalizedString
			/**
			 * scheduled
			 */
			scheduled: () => LocalizedString
			/**
			 * terminated
			 */
			terminated: () => LocalizedString
			/**
			 * vacant
			 */
			vacant: () => LocalizedString
		}
		statusDescriptions: {
			/**
			 * active; payments on track
			 */
			active: () => LocalizedString
			/**
			 * ended; not paid in full
			 */
			defaulted: () => LocalizedString
			/**
			 * ended; paid in full
			 */
			expired: () => LocalizedString
			/**
			 * active; paid in full
			 */
			fulfilled: () => LocalizedString
			/**
			 * held by a contract running today
			 */
			occupied: () => LocalizedString
			/**
			 * past its end date and still owing
			 */
			overdue: () => LocalizedString
			/**
			 * scheduled; starts in the future
			 */
			scheduled: () => LocalizedString
			/**
			 * manually terminated; locked for changes
			 */
			terminated: () => LocalizedString
			/**
			 * held by no contract today
			 */
			vacant: () => LocalizedString
		}
		table: {
			/**
			 * go to first page
			 */
			goToFirstPage: () => LocalizedString
			/**
			 * go to last page
			 */
			goToLastPage: () => LocalizedString
			/**
			 * go to next page
			 */
			goToNextPage: () => LocalizedString
			/**
			 * go to previous page
			 */
			goToPreviousPage: () => LocalizedString
			/**
			 * page {page} of {count}
			 */
			pageOf: (arg: { count: unknown, page: unknown }) => LocalizedString
			/**
			 * {count|number} result(s)
			 */
			results: (arg: { count: unknown }) => LocalizedString
			/**
			 * rows per page
			 */
			rowsPerPage: () => LocalizedString
			/**
			 * {selected} of {total} row(s) selected.
			 */
			rowsSelected: (arg: { selected: unknown, total: unknown }) => LocalizedString
			/**
			 * search...
			 */
			searchPlaceholder: () => LocalizedString
		}
		time: {
			/**
			 * {count} day
			 */
			day: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count} days
			 */
			days: (arg: { count: unknown }) => LocalizedString
		}
		undo: {
			/**
			 * changing the units of {record}
			 */
			assigned: (arg: { record: string }) => LocalizedString
			/**
			 * creating {record}
			 */
			created: (arg: { record: string }) => LocalizedString
			/**
			 * deleting {record}
			 */
			deleted: (arg: { record: string }) => LocalizedString
			/**
			 * editing {record}
			 */
			edited: (arg: { record: string }) => LocalizedString
			/**
			 * redo
			 */
			redo: () => LocalizedString
			/**
			 * {change} applied again
			 */
			redone: (arg: { change: string }) => LocalizedString
			/**
			 * terminating {record}
			 */
			terminated: (arg: { record: string }) => LocalizedString
			/**
			 * undo
			 */
			undo: () => LocalizedString
			/**
			 * {change} undone
			 */
			undone: (arg: { change: string }) => LocalizedString
			/**
			 * restoring {record}
			 */
			unterminated: (arg: { record: string }) => LocalizedString
		}
		window: {
			/**
			 * close window
			 */
			close: () => LocalizedString
			/**
			 * minimize window
			 */
			minimize: () => LocalizedString
			/**
			 * toggle maximize window
			 */
			toggleMaximize: () => LocalizedString
		}
		ui: {
			/**
			 * breadcrumb
			 */
			breadcrumb: () => LocalizedString
			/**
			 * close
			 */
			close: () => LocalizedString
			/**
			 * command palette
			 */
			commandPalette: () => LocalizedString
			/**
			 * search for a command to run
			 */
			commandPaletteDescription: () => LocalizedString
			/**
			 * no matches found
			 */
			commandPaletteEmpty: () => LocalizedString
			/**
			 * go to
			 */
			commandPaletteGoTo: () => LocalizedString
			/**
			 * loading
			 */
			loading: () => LocalizedString
			/**
			 * displays the mobile sidebar.
			 */
			mobileSidebarDescription: () => LocalizedString
			/**
			 * more
			 */
			more: () => LocalizedString
			/**
			 * more pages
			 */
			morePages: () => LocalizedString
			/**
			 * next
			 */
			next: () => LocalizedString
			/**
			 * next slide
			 */
			nextSlide: () => LocalizedString
			/**
			 * pagination
			 */
			pagination: () => LocalizedString
			/**
			 * previous
			 */
			previous: () => LocalizedString
			/**
			 * previous slide
			 */
			previousSlide: () => LocalizedString
			/**
			 * search
			 */
			search: () => LocalizedString
			/**
			 * sidebar
			 */
			sidebar: () => LocalizedString
			/**
			 * toggle sidebar
			 */
			toggleSidebar: () => LocalizedString
		}
		deleteDialog: {
			/**
			 * {count|number} contract(s) still mention it
			 */
			blockedContracts: (arg: { count: unknown }) => LocalizedString
			/**
			 * this cannot be deleted while the following still depend on it.
			 */
			blockedDescription: () => LocalizedString
			/**
			 * {count|number} payment(s) recorded against it
			 */
			blockedPayments: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count|number} unit(s) belong to it
			 */
			blockedUnits: (arg: { count: unknown }) => LocalizedString
			/**
			 * are you sure you want to delete this record?
			 */
			description: () => LocalizedString
			/**
			 * confirmation
			 */
			title: () => LocalizedString
		}
	}
	layout: {
		error: {
			/**
			 * something went wrong on this screen. going back to the dashboard usually clears it.
			 */
			description: () => LocalizedString
			/**
			 * go to dashboard
			 */
			goHome: () => LocalizedString
			/**
			 * this screen could not be shown
			 */
			title: () => LocalizedString
		}
		startup: {
			/**
			 * open the current workspace locally, or link Google Drive now to turn it into a synced workspace.
			 */
			accountChoiceDescription: () => LocalizedString
			/**
			 * no workspace profiles are available yet.
			 */
			accountChoiceEmpty: () => LocalizedString
			/**
			 * workspace
			 */
			accountChoiceTitle: () => LocalizedString
			/**
			 * there was a problem connecting the database or running startup sync.
			 */
			failedToStartDescription: () => LocalizedString
			/**
			 * failed to start the app.
			 */
			failedToStartFallback: () => LocalizedString
			/**
			 * failed to start the app
			 */
			failedToStartTitle: () => LocalizedString
			/**
			 * previous version
			 */
			previousVersion: () => LocalizedString
			/**
			 * rentable detected update recovery while starting v{version}. retry startup, or open the previous release if you need to reinstall it.
			 */
			recoveryDescription: (arg: { version: unknown }) => LocalizedString
			/**
			 * the protected backup was created from v{backupVersion}. if startup still fails, reinstall the previous release before opening rentable again.
			 */
			recoveryDetails: (arg: { backupVersion: unknown }) => LocalizedString
			/**
			 * update recovery required
			 */
			recoveryRequiredTitle: () => LocalizedString
			/**
			 * rollback completed but the recovery snapshot was not updated.
			 */
			recoverySnapshotNotUpdated: () => LocalizedString
			/**
			 * restored backup
			 */
			restoredBackup: () => LocalizedString
			/**
			 * the protected database backup has been restored and the app is locked until you reinstall the previous release.
			 */
			rolledBackDescription: () => LocalizedString
			/**
			 * open the previous github release, reinstall it, then launch rentable again.
			 */
			rolledBackDetails: () => LocalizedString
			/**
			 * update rolled back
			 */
			rolledBackTitle: () => LocalizedString
			/**
			 * backup
			 */
			startupRecoveryBackup: () => LocalizedString
		}
	}
	dashboard: {
		empty: {
			/**
			 * nothing is overdue, behind on payment, or ending inside the notice window.
			 */
			description: () => LocalizedString
			/**
			 * nothing needs doing today.
			 */
			title: () => LocalizedString
		}
		figures: {
			/**
			 * collected this month
			 */
			collectedThisMonth: () => LocalizedString
			/**
			 * occupied units
			 */
			occupiedUnits: () => LocalizedString
			/**
			 * outstanding
			 */
			outstanding: () => LocalizedString
		}
		sections: {
			/**
			 * also ending
			 */
			alsoEnding: () => LocalizedString
			/**
			 * {count|number} contract(s)
			 */
			contractCount: (arg: { count: unknown }) => LocalizedString
			/**
			 * open the contract for {tenant}
			 */
			openContract: (arg: { tenant: unknown }) => LocalizedString
			/**
			 * see all ({count|number})
			 */
			seeAll: (arg: { count: unknown }) => LocalizedString
		}
		/**
		 * dashboard
		 */
		title: () => LocalizedString
	}
	settings: {
		/**
		 * current app details and the latest synchronization and snapshot timestamps.
		 */
		aboutDescription: () => LocalizedString
		/**
		 * about
		 */
		aboutTitle: () => LocalizedString
		/**
		 * created {value}
		 */
		createdAt: (arg: { value: unknown }) => LocalizedString
		/**
		 * backups are stored in the app backup directory and can be restored below. protected update backups are created automatically before migrations run.
		 */
		createBackupDescription: () => LocalizedString
		/**
		 * create backup
		 */
		createBackupTitle: () => LocalizedString
		/**
		 * switch the active database, fall back to the default path, create backups, and restore earlier backups.
		 */
		databaseDescription: () => LocalizedString
		/**
		 * database path and backups
		 */
		databaseTitle: () => LocalizedString
		/**
		 * are you sure you want to delete this backup? this cannot be undone.
		 */
		deleteBackupDescription: () => LocalizedString
		/**
		 * are you sure you want to delete "{name}"? this cannot be undone.
		 */
		deleteBackupNamedDescription: (arg: { name: unknown }) => LocalizedString
		/**
		 * delete backup
		 */
		deleteBackupTitle: () => LocalizedString
		/**
		 * manage the ending-soon notice window, app updates, sync workspaces, and app details.
		 */
		description: () => LocalizedString
		/**
		 * rentable records what it does on this machine — startups, migrations, backups, and sync — so a failure can be looked into afterwards. the files never leave this machine and are limited in size, and passwords and account tokens are stripped out before anything is written.
		 */
		diagnosticsDescription: () => LocalizedString
		/**
		 * log location
		 */
		diagnosticsLocationLabel: () => LocalizedString
		/**
		 * open log folder
		 */
		diagnosticsReveal: () => LocalizedString
		/**
		 * diagnostics
		 */
		diagnosticsTitle: () => LocalizedString
		/**
		 * downloading update
		 */
		downloadingUpdate: () => LocalizedString
		/**
		 * choose how many days before contract end a contract should appear as ending soon on the dashboard.
		 */
		endingSoonDescription: () => LocalizedString
		/**
		 * ending soon notice window must be greater than zero
		 */
		endingSoonInvalid: () => LocalizedString
		/**
		 * ending soon notice window
		 */
		endingSoonTitle: () => LocalizedString
		/**
		 * diagnostics
		 */
		groupDiagnostics: () => LocalizedString
		/**
		 * general
		 */
		groupGeneral: () => LocalizedString
		/**
		 * updates
		 */
		groupUpdates: () => LocalizedString
		/**
		 * workspace
		 */
		groupWorkspace: () => LocalizedString
		/**
		 * you're already on the latest release.
		 */
		latestRelease: () => LocalizedString
		/**
		 * there was a problem loading the current settings snapshot.
		 */
		loadErrorDescription: () => LocalizedString
		/**
		 * settings are unavailable right now
		 */
		loadErrorTitle: () => LocalizedString
		/**
		 * open workspace
		 */
		openWorkspaceAction: () => LocalizedString
		/**
		 * protected update backup
		 */
		protectedUpdateBackup: () => LocalizedString
		/**
		 * update v{version} is available.
		 */
		releaseAvailable: (arg: { version: unknown }) => LocalizedString
		/**
		 * restore backup
		 */
		restoreBackupTitle: () => LocalizedString
		/**
		 * the update has been installed. on windows the app may close automatically during installation; otherwise restart rentable to finish switching versions.
		 */
		restartNotice: () => LocalizedString
		/**
		 * no backups are available yet.
		 */
		noBackups: () => LocalizedString
		/**
		 * leave this empty to use the default path above. saving reconnects immediately, and startup reruns migrations on the selected database path.
		 */
		pathOverrideDescription: () => LocalizedString
		/**
		 * leave empty to use the default database path
		 */
		pathOverridePlaceholder: () => LocalizedString
		/**
		 * latest snapshot
		 */
		latestSnapshot: () => LocalizedString
		/**
		 * snapshot
		 */
		snapshotNow: () => LocalizedString
		/**
		 * snapshots are managed automatically for recovery, sync, and unlink cleanup, and older internal snapshots are cleaned up for you.
		 */
		syncAutomationDescription: () => LocalizedString
		/**
		 * managed snapshots
		 */
		syncAutomationTitle: () => LocalizedString
		/**
		 * linked Google Drive accounts stay available for workspace switching, sync, and startup selection.
		 */
		syncAccountsDescription: () => LocalizedString
		/**
		 * linked Google Drive accounts
		 */
		syncAccountsTitle: () => LocalizedString
		/**
		 * needs reconnect
		 */
		syncAccountStatusNeedsReconnect: () => LocalizedString
		/**
		 * awaiting authorization
		 */
		syncAccountStatusPending: () => LocalizedString
		/**
		 * ready to sync
		 */
		syncAccountStatusReady: () => LocalizedString
		/**
		 * rentable sync storage: {value}
		 */
		syncAppDriveUsageDescription: (arg: { value: unknown }) => LocalizedString
		/**
		 * linked Google Drive
		 */
		syncConnectedAccountLabel: () => LocalizedString
		/**
		 * open without syncing for now
		 */
		syncConflictDeferAction: () => LocalizedString
		/**
		 * Google Drive metadata can no longer be read safely. Repair the remote workspace with your current local workspace before syncing again.
		 */
		syncCorruptDescription: () => LocalizedString
		/**
		 * repair remote with local
		 */
		syncCorruptKeepLocalAction: () => LocalizedString
		/**
		 * use this device as the source of truth and write a clean manifest back to Google Drive.
		 */
		syncCorruptLocalDescription: () => LocalizedString
		/**
		 * the Google Drive metadata for {email} is corrupted, so the remote copy cannot be trusted until it is repaired.
		 */
		syncCorruptRemoteDescription: (arg: { email: unknown }) => LocalizedString
		/**
		 * Google Drive metadata is corrupted. Repair the remote workspace with your local copy before syncing again.
		 */
		syncCorruptShortDescription: () => LocalizedString
		/**
		 * repair Google Drive metadata
		 */
		syncCorruptTitle: () => LocalizedString
		/**
		 * another Google Drive sync is already running. please wait for it to finish and try again.
		 */
		syncAlreadyRunningDescription: () => LocalizedString
		/**
		 * this workspace changed locally and in Google Drive since the last sync. choose which copy should continue before syncing again.
		 */
		syncConflictDescription: () => LocalizedString
		/**
		 * latest
		 */
		syncConflictLatestBadge: () => LocalizedString
		/**
		 * keep local & sync
		 */
		syncConflictKeepLocalAction: () => LocalizedString
		/**
		 * keep this device as the source of truth and overwrite the current Google Drive snapshot with the local workspace.
		 */
		syncConflictLocalDescription: () => LocalizedString
		/**
		 * replace this device with the Google Drive snapshot linked to {email}.
		 */
		syncConflictRemoteDescription: (arg: { email: unknown }) => LocalizedString
		/**
		 * this workspace diverged locally and remotely. choose which side should win before syncing again.
		 */
		syncConflictShortDescription: () => LocalizedString
		/**
		 * resolve the sync conflict
		 */
		syncConflictTitle: () => LocalizedString
		/**
		 * use remote & sync
		 */
		syncConflictUseRemoteAction: () => LocalizedString
		/**
		 * see the current workspace status, keep a fresh snapshot, and link or unlink Google Drive sync.
		 */
		syncDescription: () => LocalizedString
		/**
		 * Google Drive account linking is not configured in this build yet. The workspace and snapshot foundation is ready for it.
		 */
		syncGoogleDrivePending: () => LocalizedString
		/**
		 * this workspace already has both a local snapshot and a Google Drive snapshot. choose which copy should continue before sync starts.
		 */
		syncLinkConflictDescription: () => LocalizedString
		/**
		 * continue with this device and overwrite Google Drive with the latest local snapshot.
		 */
		syncLinkConflictLocalDescription: () => LocalizedString
		/**
		 * replace this device with the Google Drive snapshot linked to {email}.
		 */
		syncLinkConflictRemoteDescription: (arg: { email: unknown }) => LocalizedString
		/**
		 * finish linking by choosing whether the local or remote snapshot should become the synced workspace.
		 */
		syncLinkConflictShortDescription: () => LocalizedString
		/**
		 * choose which workspace copy to keep
		 */
		syncLinkConflictTitle: () => LocalizedString
		/**
		 * keep local & link
		 */
		syncLinkKeepLocalAction: () => LocalizedString
		/**
		 * use remote & link
		 */
		syncLinkUseRemoteAction: () => LocalizedString
		/**
		 * latest remote update {value}
		 */
		syncLastRemoteDescription: (arg: { value: unknown }) => LocalizedString
		/**
		 * latest snapshot {value}
		 */
		syncLastSnapshotDescription: (arg: { value: unknown }) => LocalizedString
		/**
		 * link Google Drive to this workspace to enable startup sync and remote recovery. if both local and remote snapshots exist, you will choose which one to keep.
		 */
		syncLinkDescription: () => LocalizedString
		/**
		 * Google authorization was received. Rentable is finishing the Google Drive link and checking the remote workspace now.
		 */
		syncLinkFinalizingDescription: () => LocalizedString
		/**
		 * Finishing Google Drive link
		 */
		syncLinkFinalizingTitle: () => LocalizedString
		/**
		 * complete the Google sign-in in your browser. if Google Drive already has a snapshot for this workspace, you will choose local or remote next.
		 */
		syncLinkPendingDescription: () => LocalizedString
		/**
		 * Waiting for Google authorization
		 */
		syncLinkPendingTitle: () => LocalizedString
		/**
		 * Google Drive authorization took too long to finish. Start the link again when you are ready.
		 */
		syncLinkTimedOutDescription: () => LocalizedString
		/**
		 * the current workspace is not linked to Google Drive.
		 */
		syncNotLinkedDescription: () => LocalizedString
		/**
		 * no Google Drive accounts are linked yet.
		 */
		syncNoLinkedAccounts: () => LocalizedString
		/**
		 * each workspace keeps its own local database path and latest recovery snapshot.
		 */
		syncProfilesDescription: () => LocalizedString
		/**
		 * workspace profiles
		 */
		syncProfilesTitle: () => LocalizedString
		/**
		 * Google Drive
		 */
		syncProviderGoogleDrive: () => LocalizedString
		/**
		 * local workspace
		 */
		syncProviderLocal: () => LocalizedString
		/**
		 * Google Drive authorization expired. Please reconnect the account.
		 */
		syncReconnectDescription: () => LocalizedString
		/**
		 * reset remote & relink
		 */
		syncRelinkRequiredAction: () => LocalizedString
		/**
		 * the linked Google Drive workspace is missing its manifest and the remaining remote snapshots cannot be trusted as-is. to continue safely, reset the broken remote copy and link Google Drive again. this clears the current remote snapshot files before relinking.
		 */
		syncRelinkRequiredDescription: () => LocalizedString
		/**
		 * keep the current local workspace on this device, clear the broken remote copy, and start a fresh Google Drive link.
		 */
		syncRelinkRequiredLocalDescription: () => LocalizedString
		/**
		 * the remaining Google Drive snapshot files for {email} cannot be turned back into a safe remote manifest automatically.
		 */
		syncRelinkRequiredRemoteDescription: (arg: { email: unknown }) => LocalizedString
		/**
		 * the linked Google Drive copy is broken and must be relinked before sync can continue.
		 */
		syncRelinkRequiredShortDescription: () => LocalizedString
		/**
		 * relink the broken Google Drive workspace
		 */
		syncRelinkRequiredTitle: () => LocalizedString
		/**
		 * Google Drive changed while syncing. Retry with the latest remote state.
		 */
		syncRemoteStateChangedDescription: () => LocalizedString
		/**
		 * no remote snapshot is available in Google Drive for this workspace yet.
		 */
		syncRemoteSnapshotUnavailableDescription: () => LocalizedString
		/**
		 * unlink keeps this workspace local, creates one fresh local snapshot, and stops future Google Drive syncs until you link again.
		 */
		syncUnlinkDescription: () => LocalizedString
		/**
		 * this keeps your local workspace and stops future Google Drive syncs until you link again.
		 */
		syncUnlinkDialogDescription: () => LocalizedString
		/**
		 * unlink Google Drive?
		 */
		syncUnlinkDialogTitle: () => LocalizedString
		/**
		 * the active workspace changed before Google Drive sync could start.
		 */
		syncWorkspaceChangedDescription: () => LocalizedString
		/**
		 * synced
		 */
		syncWorkspaceStatusSynced: () => LocalizedString
		/**
		 * workspace
		 */
		syncTitle: () => LocalizedString
		/**
		 * choose your preferred display language. the interface updates immediately.
		 */
		localeDescription: () => LocalizedString
		/**
		 * display language
		 */
		localeLabel: () => LocalizedString
		/**
		 * language
		 */
		localeTitle: () => LocalizedString
		/**
		 * settings
		 */
		title: () => LocalizedString
		/**
		 * checking for updates...
		 */
		updatesChecking: () => LocalizedString
		/**
		 * check github releases for a newer signed build. if startup later fails after an update, rentable offers rollback to the protected pre-update backup.
		 */
		updatesDescription: () => LocalizedString
		/**
		 * app updates
		 */
		updatesTitle: () => LocalizedString
		/**
		 * the app is currently using a custom database path override.
		 */
		usingCustomDatabasePath: () => LocalizedString
		/**
		 * the app is currently using the default database path.
		 */
		usingDefaultDatabasePath: () => LocalizedString
	}
	complexes: {
		hooks: {
			/**
			 * complex created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * complex deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * unit created successfully!
			 */
			unitCreateSuccess: () => LocalizedString
			/**
			 * unit deleted successfully!
			 */
			unitDeleteSuccess: () => LocalizedString
			/**
			 * unit updated successfully!
			 */
			unitUpdateSuccess: () => LocalizedString
			/**
			 * complex updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		form: {
			/**
			 * name is associated with a previously registered complex.
			 */
			duplicateName: () => LocalizedString
			/**
			 * {name} is already in the list.
			 */
			duplicateUnitName: (arg: { name: string }) => LocalizedString
			/**
			 * two units share a name; each needs its own.
			 */
			duplicateUnitNames: () => LocalizedString
			/**
			 * no units yet. add them here, or later from the complex itself.
			 */
			noUnitsYet: () => LocalizedString
			/**
			 * unit name
			 */
			unitName: () => LocalizedString
		}
		units: {
			/**
			 * contracts that mention this unit will appear here.
			 */
			contractsEmptyDescription: () => LocalizedString
			/**
			 * no contracts mention this unit
			 */
			contractsEmptyTitle: () => LocalizedString
			/**
			 * name is associated with a unit in the same complex.
			 */
			duplicateName: () => LocalizedString
			/**
			 * units management
			 */
			management: () => LocalizedString
		}
	}
	tenants: {
		contracts: {
			/**
			 * no contracts yet
			 */
			emptyTitle: () => LocalizedString
			/**
			 * contracts this tenant holds will appear here.
			 */
			emptyDescription: () => LocalizedString
		}
		hooks: {
			/**
			 * tenant created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * tenant deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * tenant updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		form: {
			/**
			 * country code
			 */
			phoneCountryCode: () => LocalizedString
			/**
			 * national id is associated with a registered tenant.
			 */
			duplicateNationalId: () => LocalizedString
			/**
			 * phone is associated with a registered tenant.
			 */
			duplicatePhone: () => LocalizedString
			/**
			 * national identity number must start with 1 or 2 and be 10 digits long.
			 */
			invalidNationalId: () => LocalizedString
			/**
			 * phone must be valid for the selected country code {countryCode}.
			 */
			invalidPhone: (arg: { countryCode: unknown }) => LocalizedString
			/**
			 * 5xxxxxxxx
			 */
			phoneNumberPlaceholder: () => LocalizedString
			/**
			 * phone (+966...)
			 */
			phonePlaceholder: () => LocalizedString
		}
	}
	contracts: {
		form: {
			/**
			 * start date
			 */
			startDate: () => LocalizedString
			/**
			 * end date
			 */
			calculatedEndDate: () => LocalizedString
			/**
			 * updated automatically from the selected cycle, start date, and number of cycles. you can manually adjust it within {days} days before or after the suggested end date; allowed dates are highlighted in green.
			 */
			calculatedEndDateHint: (arg: { days: unknown }) => LocalizedString
			/**
			 * cost can have at most two decimal places.
			 */
			costDecimalPlaces: () => LocalizedString
			/**
			 * cost must be greater than zero.
			 */
			costGreaterThanZero: () => LocalizedString
			/**
			 * cost per payment must be greater than zero.
			 */
			costPerPaymentGreaterThanZero: () => LocalizedString
			/**
			 * cost is required.
			 */
			costRequired: () => LocalizedString
			/**
			 * number of cycles must be greater than zero.
			 */
			cyclesGreaterThanZero: () => LocalizedString
			/**
			 * number of cycles is required.
			 */
			cyclesRequired: () => LocalizedString
			/**
			 * government id is associated with another contract.
			 */
			duplicateGovernmentId: () => LocalizedString
			/**
			 * end date must be after start date.
			 */
			endDateAfterStart: () => LocalizedString
			/**
			 * end date is required.
			 */
			endDateRequired: () => LocalizedString
			/**
			 * end date
			 */
			endDateShort: () => LocalizedString
			/**
			 * please select a valid tenant.
			 */
			invalidTenant: () => LocalizedString
			/**
			 * loading tenant...
			 */
			loadingTenant: () => LocalizedString
			/**
			 * loading tenants...
			 */
			loadingTenants: () => LocalizedString
			/**
			 * no tenant found.
			 */
			noTenantFound: () => LocalizedString
			/**
			 * number of cycles
			 */
			numberOfCycles: () => LocalizedString
			/**
			 * total expected amount
			 */
			totalExpectedAmount: () => LocalizedString
			/**
			 * payment amount can have at most two decimal places
			 */
			paymentAmountDecimalPlaces: () => LocalizedString
			/**
			 * payment amount must be greater than zero
			 */
			paymentAmountGreaterThanZero: () => LocalizedString
			/**
			 * payment amount is required
			 */
			paymentAmountRequired: () => LocalizedString
			/**
			 * payment date is required
			 */
			paymentDateRequired: () => LocalizedString
			/**
			 * pick a date
			 */
			pickDate: () => LocalizedString
			/**
			 * pick a date range
			 */
			pickDateRange: () => LocalizedString
			/**
			 * end date must stay within {days} days before or after the calculated {interval} cycle end date.
			 */
			periodMustMatchWholeCycles: (arg: { days: unknown, interval: unknown }) => LocalizedString
			/**
			 * search and select tenant
			 */
			searchAndSelectTenant: () => LocalizedString
			/**
			 * search tenant by name, id or phone...
			 */
			searchTenantPlaceholder: () => LocalizedString
			/**
			 * start date is required.
			 */
			startDateRequired: () => LocalizedString
			/**
			 * tenant is required.
			 */
			tenantRequired: () => LocalizedString
		}
		hooks: {
			/**
			 * payment created successfully!
			 */
			createPaymentSuccess: () => LocalizedString
			/**
			 * contract created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * payment deleted successfully!
			 */
			deletePaymentSuccess: () => LocalizedString
			/**
			 * contract deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * contract restored successfully!
			 */
			restoreSuccess: () => LocalizedString
			/**
			 * contract terminated successfully!
			 */
			terminateSuccess: () => LocalizedString
			/**
			 * payment updated successfully!
			 */
			updatePaymentSuccess: () => LocalizedString
			/**
			 * contract updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		intervals: {
			/**
			 * annual
			 */
			annual: () => LocalizedString
			/**
			 * monthly
			 */
			monthly: () => LocalizedString
			/**
			 * quarterly
			 */
			quarterly: () => LocalizedString
			/**
			 * semi-annual
			 */
			semiAnnual: () => LocalizedString
		}
		payments: {
			/**
			 * this contract has already reached its required total payment amount. you can still edit or delete payments if needed, but you cannot add more until the paid total drops below the required amount.
			 */
			fullyPaidNotice: () => LocalizedString
			/**
			 * this contract has been fully paid. you can edit or delete payments, but you cannot add more.
			 */
			fullyPaidSummary: () => LocalizedString
			/**
			 * total shown for {month}
			 */
			monthTotal: (arg: { month: unknown }) => LocalizedString
			/**
			 * {percent}% fulfilled
			 */
			percentFulfilled: (arg: { percent: unknown }) => LocalizedString
			/**
			 * {amount} sar remaining
			 */
			remaining: (arg: { amount: unknown }) => LocalizedString
			/**
			 * remaining after this payment
			 */
			remainingAfter: () => LocalizedString
			/**
			 * remaining balance
			 */
			remainingBalance: () => LocalizedString
			/**
			 * terminated contracts are locked. you can review payment history here, but you cannot add, edit, or delete payments until the contract is unterminated.
			 */
			terminatedNotice: () => LocalizedString
			/**
			 * this contract is terminated and locked. payment records are read-only.
			 */
			terminatedSummary: () => LocalizedString
			/**
			 * payments
			 */
			title: () => LocalizedString
			/**
			 * payments for {govId}
			 */
			titleFor: (arg: { govId: unknown }) => LocalizedString
			/**
			 * track contract payments and add new payment records here.
			 */
			trackSummary: () => LocalizedString
		}
		ranks: {
			/**
			 * ending soon
			 */
			endingSoon: () => LocalizedString
			/**
			 * overdue
			 */
			overdue: () => LocalizedString
			/**
			 * owing
			 */
			owing: () => LocalizedString
		}
		table: {
			/**
			 * payments management
			 */
			paymentsManagement: () => LocalizedString
			/**
			 * are you sure you want to remove the manual termination from this contract?
			 */
			restoreDescription: () => LocalizedString
			/**
			 * restore contract
			 */
			restoreTitle: () => LocalizedString
			/**
			 * are you sure you want to manually terminate this contract? this only works for active or past contracts.
			 */
			terminateDescription: () => LocalizedString
			/**
			 * terminate contract
			 */
			terminateTitle: () => LocalizedString
			/**
			 * tenant #{tenantId}
			 */
			tenantFallback: (arg: { tenantId: unknown }) => LocalizedString
			/**
			 * units management
			 */
			unitsManagement: () => LocalizedString
		}
		units: {
			/**
			 * available
			 */
			available: () => LocalizedString
			/**
			 * assigned
			 */
			assigned: () => LocalizedString
			/**
			 * move a unit between the two sides; each move is saved as it happens. units linked to a contract whose term overlaps this one are not offered.
			 */
			transferDescription: () => LocalizedString
			/**
			 * contracts with registered payments are locked. you can review linked units here, but you cannot assign or remove units after payments have been recorded.
			 */
			lockNoticeHasPayments: () => LocalizedString
			/**
			 * terminated contracts are locked. you can review linked units here, but you cannot assign or remove units until the contract is unterminated.
			 */
			lockNoticeTerminated: () => LocalizedString
			/**
			 * no units are assigned to this contract yet.
			 */
			noAssignedUnits: () => LocalizedString
			/**
			 * no units are available for this contract timeframe.
			 */
			noAvailableUnits: () => LocalizedString
		}
	}
	settingsHooks: {
		/**
		 * backup created successfully!
		 */
		backupCreated: () => LocalizedString
		/**
		 * backup deleted successfully!
		 */
		backupDeleted: () => LocalizedString
		/**
		 * backup restored successfully!
		 */
		backupRestored: () => LocalizedString
		/**
		 * database path reset to default successfully!
		 */
		databasePathReset: () => LocalizedString
		/**
		 * database path updated successfully!
		 */
		databasePathUpdated: () => LocalizedString
		/**
		 * ending soon notice window updated successfully!
		 */
		endingSoonUpdated: () => LocalizedString
		/**
		 * Google Drive workspace is already up to date!
		 */
		googleDriveAlreadyUpToDate: () => LocalizedString
		/**
		 * Google Drive account disconnected successfully!
		 */
		googleDriveDisconnected: () => LocalizedString
		/**
		 * Google Drive workspace linked successfully!
		 */
		googleDriveLinked: () => LocalizedString
		/**
		 * Google Drive workspace unlinked successfully!
		 */
		googleDriveUnlinked: () => LocalizedString
		/**
		 * Google Drive workspace synchronized successfully!
		 */
		googleDriveSynchronized: () => LocalizedString
		/**
		 * workspace switched successfully!
		 */
		profileSwitched: () => LocalizedString
		/**
		 * protected update backup restored successfully!
		 */
		rollbackRestored: () => LocalizedString
		/**
		 * snapshot created successfully!
		 */
		snapshotCreated: () => LocalizedString
		/**
		 * startup recovery cleared. retrying the current version is now allowed.
		 */
		startupRecoveryCleared: () => LocalizedString
	}
}

export type Formatters = {
	number: (value: unknown) => unknown
}
