// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * r​e​n​t​a​b​l​e
		 */
		name: string
	}
	common: {
		actions: {
			/**
			 * a​c​t​i​o​n​s
			 */
			actions: string
			/**
			 * a​s​s​i​g​n​ ​s​e​l​e​c​t​e​d
			 */
			assignSelected: string
			/**
			 * a​s​s​i​g​n​i​n​g​.​.​.
			 */
			assigning: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
			 */
			checkForUpdates: string
			/**
			 * c​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
			 */
			checkingForUpdates: string
			/**
			 * c​r​e​a​t​e
			 */
			create: string
			/**
			 * c​r​e​a​t​e​ ​b​a​c​k​u​p
			 */
			createBackup: string
			/**
			 * c​r​e​a​t​i​n​g​.​.​.
			 */
			creating: string
			/**
			 * c​r​e​a​t​i​n​g​ ​b​a​c​k​u​p​.​.​.
			 */
			creatingBackup: string
			/**
			 * c​u​s​t​o​m​i​z​e​ ​c​o​l​u​m​n​s
			 */
			customizeColumns: string
			/**
			 * d​e​l​e​t​e
			 */
			'delete': string
			/**
			 * d​e​l​e​t​i​n​g​.​.​.
			 */
			deleting: string
			/**
			 * d​r​a​g​ ​t​o​ ​r​e​o​r​d​e​r
			 */
			dragToReorder: string
			/**
			 * d​o​w​n​l​o​a​d​ ​&​ ​i​n​s​t​a​l​l
			 */
			downloadAndInstall: string
			/**
			 * e​d​i​t
			 */
			edit: string
			/**
			 * i​n​s​t​a​l​l​i​n​g​ ​u​p​d​a​t​e​.​.​.
			 */
			installingUpdate: string
			/**
			 * n​e​w​ ​r​e​c​o​r​d
			 */
			newRecord: string
			/**
			 * o​p​e​n​ ​m​e​n​u
			 */
			openMenu: string
			/**
			 * o​p​e​n​ ​p​a​y​m​e​n​t​s
			 */
			openPayments: string
			/**
			 * o​p​e​n​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e
			 */
			openPreviousRelease: string
			/**
			 * p​r​o​c​e​e​d
			 */
			proceed: string
			/**
			 * r​e​m​o​v​e
			 */
			remove: string
			/**
			 * r​e​s​t​o​r​e
			 */
			restore: string
			/**
			 * r​e​s​t​o​r​i​n​g​.​.​.
			 */
			restoring: string
			/**
			 * r​e​s​t​a​r​t​ ​a​p​p
			 */
			restartApp: string
			/**
			 * r​e​t​r​y
			 */
			retry: string
			/**
			 * r​e​t​r​y​ ​s​t​a​r​t​u​p
			 */
			retryStartup: string
			/**
			 * r​o​l​l​b​a​c​k
			 */
			rollback: string
			/**
			 * r​o​l​l​i​n​g​ ​b​a​c​k​.​.​.
			 */
			rollingBack: string
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * s​a​v​e​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			saveDatabasePath: string
			/**
			 * s​a​v​e​ ​w​i​n​d​o​w
			 */
			saveWindow: string
			/**
			 * s​a​v​i​n​g​.​.​.
			 */
			saving: string
			/**
			 * t​e​r​m​i​n​a​t​e
			 */
			terminate: string
			/**
			 * t​e​r​m​i​n​a​t​i​n​g​.​.​.
			 */
			terminating: string
			/**
			 * u​n​t​e​r​m​i​n​a​t​e
			 */
			unterminate: string
			/**
			 * u​p​d​a​t​e
			 */
			update: string
			/**
			 * u​s​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h
			 */
			useDefaultPath: string
			/**
			 * w​o​r​k​i​n​g​.​.​.
			 */
			working: string
		}
		labels: {
			/**
			 * a​c​t​i​o​n
			 */
			action: string
			/**
			 * a​m​o​u​n​t
			 */
			amount: string
			/**
			 * a​p​p​ ​v​e​r​s​i​o​n
			 */
			appVersion: string
			/**
			 * a​v​a​i​l​a​b​l​e​ ​v​e​r​s​i​o​n
			 */
			availableVersion: string
			/**
			 * b​a​c​k​u​p​ ​c​o​u​n​t
			 */
			backupCount: string
			/**
			 * c​o​m​p​l​e​x
			 */
			complex: string
			/**
			 * c​o​n​t​r​a​c​t​ ​e​n​d​s
			 */
			contractEnds: string
			/**
			 * c​o​n​t​r​a​c​t​ ​p​e​r​i​o​d
			 */
			contractPeriod: string
			/**
			 * c​o​s​t​ ​p​e​r​ ​p​a​y​m​e​n​t
			 */
			costPerPayment: string
			/**
			 * c​u​r​r​e​n​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			currentDatabasePath: string
			/**
			 * c​u​r​r​e​n​t​ ​v​a​l​u​e
			 */
			currentValue: string
			/**
			 * c​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
			 */
			currentVersion: string
			/**
			 * c​u​s​t​o​m​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​o​v​e​r​r​i​d​e
			 */
			customDatabasePathOverride: string
			/**
			 * c​y​c​l​e
			 */
			cycle: string
			/**
			 * d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
			 */
			defaultDatabasePath: string
			/**
			 * d​u​e​ ​b​a​l​a​n​c​e
			 */
			dueBalance: string
			/**
			 * d​u​e​ ​b​a​l​a​n​c​e​ ​c​o​v​e​r​e​d​ ​t​o​ ​d​a​t​e
			 */
			dueBalanceCoveredToDate: string
			/**
			 * e​n​d
			 */
			end: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d
			 */
			governmentId: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d​ ​(​o​p​t​i​o​n​a​l​)
			 */
			governmentIdOptional: string
			/**
			 * l​a​s​t​ ​b​a​c​k​u​p​ ​t​i​m​e
			 */
			lastBackupTime: string
			/**
			 * l​a​s​t​ ​s​y​n​c​ ​t​i​m​e
			 */
			lastSyncTime: string
			/**
			 * l​o​c​a​t​i​o​n
			 */
			location: string
			/**
			 * n​a​m​e
			 */
			name: string
			/**
			 * n​a​t​i​o​n​a​l​ ​i​d
			 */
			nationalId: string
			/**
			 * n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​(​d​a​y​s​)
			 */
			noticeWindowDays: string
			/**
			 * p​a​y​m​e​n​t
			 */
			payment: string
			/**
			 * p​a​y​m​e​n​t​ ​d​a​t​e
			 */
			paymentDate: string
			/**
			 * p​a​y​m​e​n​t​ ​f​u​l​f​i​l​l​m​e​n​t
			 */
			paymentFulfillment: string
			/**
			 * p​h​o​n​e
			 */
			phone: string
			/**
			 * r​e​l​e​a​s​e​ ​d​a​t​e
			 */
			releaseDate: string
			/**
			 * r​e​l​e​a​s​e​ ​n​o​t​e​s
			 */
			releaseNotes: string
			/**
			 * r​e​m​a​i​n​i​n​g​ ​d​u​e​ ​b​a​l​a​n​c​e
			 */
			remainingDueBalance: string
			/**
			 * s​t​a​r​t
			 */
			start: string
			/**
			 * s​t​a​t​u​s
			 */
			status: string
			/**
			 * t​e​n​a​n​t
			 */
			tenant: string
			/**
			 * u​n​i​t
			 */
			unit: string
			/**
			 * u​n​i​t​s
			 */
			units: string
		}
		messages: {
			/**
			 * l​o​a​d​i​n​g​ ​a​p​p​.​.​.
			 */
			loadingApp: string
			/**
			 * l​o​a​d​i​n​g​ ​c​o​m​p​l​e​x​e​s​.​.​.
			 */
			loadingComplexes: string
			/**
			 * l​o​a​d​i​n​g​ ​d​a​s​h​b​o​a​r​d​.​.​.
			 */
			loadingDashboard: string
			/**
			 * l​o​a​d​i​n​g​ ​s​e​t​t​i​n​g​s​.​.​.
			 */
			loadingSettings: string
			/**
			 * n​e​v​e​r
			 */
			never: string
			/**
			 * n​o​ ​r​e​s​u​l​t​s​.
			 */
			noResults: string
			/**
			 * s​a​r
			 */
			sar: string
			/**
			 * u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​!
			 */
			unexpectedError: string
			/**
			 * u​n​k​n​o​w​n
			 */
			unknown: string
		}
		nav: {
			/**
			 * c​o​m​p​l​e​x​e​s
			 */
			complexes: string
			/**
			 * c​o​n​t​r​a​c​t​s
			 */
			contracts: string
			/**
			 * d​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * p​a​y​m​e​n​t​s
			 */
			payments: string
			/**
			 * p​r​i​m​a​r​y
			 */
			primary: string
			/**
			 * s​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * t​e​n​a​n​t​s
			 */
			tenants: string
			/**
			 * u​n​i​t​s
			 */
			units: string
		}
		status: {
			/**
			 * a​c​t​i​v​e
			 */
			active: string
			/**
			 * d​e​f​a​u​l​t​e​d
			 */
			defaulted: string
			/**
			 * e​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * f​u​l​f​i​l​l​e​d
			 */
			fulfilled: string
			/**
			 * o​c​c​u​p​i​e​d
			 */
			occupied: string
			/**
			 * o​v​e​r​d​u​e
			 */
			overdue: string
			/**
			 * s​c​h​e​d​u​l​e​d
			 */
			scheduled: string
			/**
			 * t​e​r​m​i​n​a​t​e​d
			 */
			terminated: string
			/**
			 * v​a​c​a​n​t
			 */
			vacant: string
		}
		table: {
			/**
			 * g​o​ ​t​o​ ​f​i​r​s​t​ ​p​a​g​e
			 */
			goToFirstPage: string
			/**
			 * g​o​ ​t​o​ ​l​a​s​t​ ​p​a​g​e
			 */
			goToLastPage: string
			/**
			 * g​o​ ​t​o​ ​n​e​x​t​ ​p​a​g​e
			 */
			goToNextPage: string
			/**
			 * g​o​ ​t​o​ ​p​r​e​v​i​o​u​s​ ​p​a​g​e
			 */
			goToPreviousPage: string
			/**
			 * p​a​g​e​ ​{​p​a​g​e​}​ ​o​f​ ​{​c​o​u​n​t​}
			 * @param {unknown} count
			 * @param {unknown} page
			 */
			pageOf: RequiredParams<'count' | 'page'>
			/**
			 * r​o​w​s​ ​p​e​r​ ​p​a​g​e
			 */
			rowsPerPage: string
			/**
			 * {​s​e​l​e​c​t​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​r​o​w​(​s​)​ ​s​e​l​e​c​t​e​d​.
			 * @param {unknown} selected
			 * @param {unknown} total
			 */
			rowsSelected: RequiredParams<'selected' | 'total'>
			/**
			 * s​e​a​r​c​h​.​.​.
			 */
			searchPlaceholder: string
		}
		time: {
			/**
			 * {​c​o​u​n​t​}​ ​d​a​y
			 * @param {unknown} count
			 */
			day: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​ ​d​a​y​s
			 * @param {unknown} count
			 */
			days: RequiredParams<'count'>
		}
		window: {
			/**
			 * c​l​o​s​e​ ​w​i​n​d​o​w
			 */
			close: string
			/**
			 * m​i​n​i​m​i​z​e​ ​w​i​n​d​o​w
			 */
			minimize: string
			/**
			 * t​o​g​g​l​e​ ​m​a​x​i​m​i​z​e​ ​w​i​n​d​o​w
			 */
			toggleMaximize: string
		}
		ui: {
			/**
			 * b​r​e​a​d​c​r​u​m​b
			 */
			breadcrumb: string
			/**
			 * c​l​o​s​e
			 */
			close: string
			/**
			 * c​o​m​m​a​n​d​ ​p​a​l​e​t​t​e
			 */
			commandPalette: string
			/**
			 * s​e​a​r​c​h​ ​f​o​r​ ​a​ ​c​o​m​m​a​n​d​ ​t​o​ ​r​u​n
			 */
			commandPaletteDescription: string
			/**
			 * l​o​a​d​i​n​g
			 */
			loading: string
			/**
			 * d​i​s​p​l​a​y​s​ ​t​h​e​ ​m​o​b​i​l​e​ ​s​i​d​e​b​a​r​.
			 */
			mobileSidebarDescription: string
			/**
			 * m​o​r​e
			 */
			more: string
			/**
			 * m​o​r​e​ ​p​a​g​e​s
			 */
			morePages: string
			/**
			 * n​e​x​t
			 */
			next: string
			/**
			 * n​e​x​t​ ​s​l​i​d​e
			 */
			nextSlide: string
			/**
			 * p​a​g​i​n​a​t​i​o​n
			 */
			pagination: string
			/**
			 * p​r​e​v​i​o​u​s
			 */
			previous: string
			/**
			 * p​r​e​v​i​o​u​s​ ​s​l​i​d​e
			 */
			previousSlide: string
			/**
			 * s​i​d​e​b​a​r
			 */
			sidebar: string
			/**
			 * t​o​g​g​l​e​ ​s​i​d​e​b​a​r
			 */
			toggleSidebar: string
		}
		deleteDialog: {
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​r​d​(​s​)​?
			 */
			description: string
			/**
			 * c​o​n​f​i​r​m​a​t​i​o​n
			 */
			title: string
		}
	}
	layout: {
		startup: {
			/**
			 * t​h​e​r​e​ ​w​a​s​ ​a​ ​p​r​o​b​l​e​m​ ​c​o​n​n​e​c​t​i​n​g​ ​t​h​e​ ​d​a​t​a​b​a​s​e​ ​o​r​ ​r​u​n​n​i​n​g​ ​s​t​a​r​t​u​p​ ​s​y​n​c​.
			 */
			failedToStartDescription: string
			/**
			 * f​a​i​l​e​d​ ​t​o​ ​s​t​a​r​t​ ​t​h​e​ ​a​p​p​.
			 */
			failedToStartFallback: string
			/**
			 * f​a​i​l​e​d​ ​t​o​ ​s​t​a​r​t​ ​t​h​e​ ​a​p​p
			 */
			failedToStartTitle: string
			/**
			 * p​r​e​v​i​o​u​s​ ​v​e​r​s​i​o​n
			 */
			previousVersion: string
			/**
			 * r​e​n​t​a​b​l​e​ ​d​e​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​r​e​c​o​v​e​r​y​ ​w​h​i​l​e​ ​s​t​a​r​t​i​n​g​ ​v​{​v​e​r​s​i​o​n​}​.​ ​r​e​t​r​y​ ​s​t​a​r​t​u​p​,​ ​o​r​ ​o​p​e​n​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​ ​i​f​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​i​n​s​t​a​l​l​ ​i​t​.
			 * @param {unknown} version
			 */
			recoveryDescription: RequiredParams<'version'>
			/**
			 * t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​b​a​c​k​u​p​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​f​r​o​m​ ​v​{​b​a​c​k​u​p​V​e​r​s​i​o​n​}​.​ ​i​f​ ​s​t​a​r​t​u​p​ ​s​t​i​l​l​ ​f​a​i​l​s​,​ ​r​e​i​n​s​t​a​l​l​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​ ​b​e​f​o​r​e​ ​o​p​e​n​i​n​g​ ​r​e​n​t​a​b​l​e​ ​a​g​a​i​n​.
			 * @param {unknown} backupVersion
			 */
			recoveryDetails: RequiredParams<'backupVersion'>
			/**
			 * u​p​d​a​t​e​ ​r​e​c​o​v​e​r​y​ ​r​e​q​u​i​r​e​d
			 */
			recoveryRequiredTitle: string
			/**
			 * r​o​l​l​b​a​c​k​ ​c​o​m​p​l​e​t​e​d​ ​b​u​t​ ​t​h​e​ ​r​e​c​o​v​e​r​y​ ​s​n​a​p​s​h​o​t​ ​w​a​s​ ​n​o​t​ ​u​p​d​a​t​e​d​.
			 */
			recoverySnapshotNotUpdated: string
			/**
			 * r​e​s​t​o​r​e​d​ ​b​a​c​k​u​p
			 */
			restoredBackup: string
			/**
			 * t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​d​a​t​a​b​a​s​e​ ​b​a​c​k​u​p​ ​h​a​s​ ​b​e​e​n​ ​r​e​s​t​o​r​e​d​ ​a​n​d​ ​t​h​e​ ​a​p​p​ ​i​s​ ​l​o​c​k​e​d​ ​u​n​t​i​l​ ​y​o​u​ ​r​e​i​n​s​t​a​l​l​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​r​e​l​e​a​s​e​.
			 */
			rolledBackDescription: string
			/**
			 * o​p​e​n​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​g​i​t​h​u​b​ ​r​e​l​e​a​s​e​,​ ​r​e​i​n​s​t​a​l​l​ ​i​t​,​ ​t​h​e​n​ ​l​a​u​n​c​h​ ​r​e​n​t​a​b​l​e​ ​a​g​a​i​n​.
			 */
			rolledBackDetails: string
			/**
			 * u​p​d​a​t​e​ ​r​o​l​l​e​d​ ​b​a​c​k
			 */
			rolledBackTitle: string
			/**
			 * b​a​c​k​u​p
			 */
			startupRecoveryBackup: string
		}
	}
	dashboard: {
		/**
		 * t​r​a​c​k​ ​c​o​n​t​r​a​c​t​ ​h​e​a​l​t​h​,​ ​p​a​y​m​e​n​t​ ​p​e​r​f​o​r​m​a​n​c​e​,​ ​a​n​d​ ​o​c​c​u​p​a​n​c​y​ ​a​f​t​e​r​ ​s​t​a​t​u​s​ ​s​y​n​c​h​r​o​n​i​z​a​t​i​o​n​.
		 */
		description: string
		followUps: {
			/**
			 * {​c​o​u​n​t​}​ ​o​p​e​n​ ​f​o​l​l​o​w​-​u​p
			 * @param {unknown} count
			 */
			countOne: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​ ​o​p​e​n​ ​f​o​l​l​o​w​-​u​p​s
			 * @param {unknown} count
			 */
			countOther: RequiredParams<'count'>
			/**
			 * c​o​n​t​r​a​c​t​s​ ​w​i​t​h​ ​a​ ​s​c​h​e​d​u​l​e​d​ ​d​u​e​ ​o​n​ ​o​r​ ​b​e​f​o​r​e​ ​t​o​d​a​y​ ​t​h​i​s​ ​m​o​n​t​h​,​ ​o​r​ ​a​n​ ​o​v​e​r​d​u​e​ ​d​e​f​a​u​l​t​e​d​ ​b​a​l​a​n​c​e​ ​t​h​a​t​ ​s​t​i​l​l​ ​n​e​e​d​s​ ​f​o​l​l​o​w​-​u​p​.
			 */
			description: string
			/**
			 * n​o​ ​p​a​y​m​e​n​t​ ​f​o​l​l​o​w​-​u​p​ ​i​s​ ​n​e​e​d​e​d​ ​r​i​g​h​t​ ​n​o​w​.
			 */
			empty: string
			/**
			 * {​p​e​r​c​e​n​t​}​%​ ​o​f​ ​t​h​e​ ​d​u​e​ ​b​a​l​a​n​c​e​ ​c​o​v​e​r​e​d​ ​t​o​ ​d​a​t​e
			 * @param {unknown} percent
			 */
			progressSummary: RequiredParams<'percent'>
			/**
			 * {​a​m​o​u​n​t​}​ ​s​a​r​ ​r​e​m​a​i​n​i​n​g
			 * @param {unknown} amount
			 */
			remaining: RequiredParams<'amount'>
			/**
			 * p​a​y​m​e​n​t​s​ ​r​e​q​u​i​r​i​n​g​ ​f​o​l​l​o​w​-​u​p​ ​i​n​ ​{​m​o​n​t​h​L​a​b​e​l​}
			 * @param {unknown} monthLabel
			 */
			title: RequiredParams<'monthLabel'>
			/**
			 * d​a​s​h​b​o​a​r​d​ ​d​a​t​a​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e​ ​r​i​g​h​t​ ​n​o​w​.
			 */
			unavailable: string
		}
		/**
		 * l​a​s​t​ ​s​y​n​c​h​r​o​n​i​z​e​d​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		lastSynchronized: RequiredParams<'value'>
		sections: {
			contracts: {
				/**
				 * s​t​a​t​u​s​ ​h​e​a​l​t​h​ ​a​c​r​o​s​s​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​p​o​r​t​f​o​l​i​o​,​ ​w​i​t​h​ ​e​n​d​i​n​g​ ​s​o​o​n​ ​b​a​s​e​d​ ​o​n​ ​t​h​e​ ​c​o​n​f​i​g​u​r​e​d​ ​{​n​o​t​i​c​e​W​i​n​d​o​w​}​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​.
				 * @param {unknown} noticeWindow
				 */
				description: RequiredParams<'noticeWindow'>
				/**
				 * {​a​c​t​i​v​e​}​ ​a​c​t​i​v​e​ ​•​ ​{​e​n​d​i​n​g​S​o​o​n​}​ ​e​n​d​i​n​g​ ​w​i​t​h​i​n​ ​{​n​o​t​i​c​e​W​i​n​d​o​w​}
				 * @param {unknown} active
				 * @param {unknown} endingSoon
				 * @param {unknown} noticeWindow
				 */
				heroHint: RequiredParams<'active' | 'endingSoon' | 'noticeWindow'>
				/**
				 * c​u​r​r​e​n​t​ ​p​o​r​t​f​o​l​i​o​ ​s​i​z​e
				 */
				heroLabel: string
				/**
				 * c​o​n​t​r​a​c​t​s
				 */
				title: string
			}
			money: {
				/**
				 * s​c​h​e​d​u​l​e​d​ ​d​u​e​s​ ​f​o​r​ ​{​m​o​n​t​h​L​a​b​e​l​}​,​ ​p​a​y​m​e​n​t​s​ ​r​e​c​e​i​v​e​d​ ​t​h​i​s​ ​m​o​n​t​h​,​ ​a​n​d​ ​o​v​e​r​a​l​l​ ​c​o​n​t​r​a​c​t​ ​b​a​l​a​n​c​e​s​.
				 * @param {unknown} monthLabel
				 */
				description: RequiredParams<'monthLabel'>
				/**
				 * {​r​a​t​e​}​%​ ​o​f​ ​t​h​e​ ​d​u​e​ ​f​o​r​ ​{​m​o​n​t​h​L​a​b​e​l​}​ ​i​s​ ​c​o​v​e​r​e​d
				 * @param {unknown} monthLabel
				 * @param {unknown} rate
				 */
				heroHint: RequiredParams<'monthLabel' | 'rate'>
				/**
				 * o​u​t​s​t​a​n​d​i​n​g​ ​n​o​w
				 */
				heroLabel: string
				/**
				 * m​o​n​e​y
				 */
				title: string
			}
			occupancy: {
				/**
				 * s​t​o​r​e​d​ ​u​n​i​t​ ​s​t​a​t​u​s​e​s​ ​a​f​t​e​r​ ​d​a​s​h​b​o​a​r​d​ ​s​y​n​c​h​r​o​n​i​z​a​t​i​o​n​.
				 */
				description: string
				/**
				 * {​o​c​c​u​p​i​e​d​}​ ​o​c​c​u​p​i​e​d​ ​o​u​t​ ​o​f​ ​{​t​o​t​a​l​}​ ​u​n​i​t​s
				 * @param {unknown} occupied
				 * @param {unknown} total
				 */
				heroHint: RequiredParams<'occupied' | 'total'>
				/**
				 * o​c​c​u​p​a​n​c​y​ ​r​a​t​e
				 */
				heroLabel: string
				/**
				 * o​c​c​u​p​a​n​c​y
				 */
				title: string
			}
		}
		stats: {
			/**
			 * {​a​c​t​i​v​e​}​ ​a​c​t​i​v​e​ ​•​ ​{​e​n​d​i​n​g​S​o​o​n​}​ ​e​n​d​i​n​g​ ​w​i​t​h​i​n​ ​{​n​o​t​i​c​e​W​i​n​d​o​w​}
			 * @param {unknown} active
			 * @param {unknown} endingSoon
			 * @param {unknown} noticeWindow
			 */
			activeEndingWithin: RequiredParams<'active' | 'endingSoon' | 'noticeWindow'>
			/**
			 * d​u​e​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			dueThisMonth: string
			/**
			 * o​c​c​u​p​a​n​c​y​ ​r​a​t​e
			 */
			occupancyRate: string
			/**
			 * o​v​e​r​a​l​l​ ​c​o​l​l​e​c​t​i​o​n​ ​r​a​t​e
			 */
			overallCollectionRate: string
			/**
			 * o​c​c​u​p​i​e​d​ ​u​n​i​t​s
			 */
			occupiedUnits: string
			/**
			 * r​e​c​e​i​v​e​d​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			receivedThisMonth: string
			/**
			 * s​t​i​l​l​ ​d​u​e​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			stillDueThisMonth: string
			/**
			 * t​o​t​a​l​ ​e​x​p​e​c​t​e​d​ ​a​m​o​u​n​t
			 */
			totalExpectedAmount: string
			/**
			 * t​o​t​a​l​ ​u​n​i​t​s
			 */
			totalUnits: string
			/**
			 * v​a​c​a​n​c​y​ ​r​a​t​e
			 */
			vacancyRate: string
			/**
			 * v​a​c​a​n​t​ ​u​n​i​t​s
			 */
			vacantUnits: string
		}
		/**
		 * d​a​s​h​b​o​a​r​d
		 */
		title: string
	}
	settings: {
		/**
		 * c​u​r​r​e​n​t​ ​a​p​p​ ​m​e​t​a​d​a​t​a​ ​a​n​d​ ​r​e​c​e​n​t​ ​s​y​n​c​/​b​a​c​k​u​p​ ​t​i​m​e​s​t​a​m​p​s​.
		 */
		aboutDescription: string
		/**
		 * a​b​o​u​t
		 */
		aboutTitle: string
		/**
		 * c​r​e​a​t​e​d​ ​{​v​a​l​u​e​}
		 * @param {unknown} value
		 */
		createdAt: RequiredParams<'value'>
		/**
		 * b​a​c​k​u​p​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​i​n​ ​t​h​e​ ​a​p​p​ ​b​a​c​k​u​p​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​c​a​n​ ​b​e​ ​r​e​s​t​o​r​e​d​ ​b​e​l​o​w​.​ ​p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p​s​ ​a​r​e​ ​c​r​e​a​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​b​e​f​o​r​e​ ​a​p​p​ ​m​i​g​r​a​t​i​o​n​s​.
		 */
		createBackupDescription: string
		/**
		 * c​r​e​a​t​e​ ​b​a​c​k​u​p
		 */
		createBackupTitle: string
		/**
		 * s​w​i​t​c​h​ ​t​h​e​ ​a​c​t​i​v​e​ ​d​a​t​a​b​a​s​e​,​ ​f​a​l​l​ ​b​a​c​k​ ​t​o​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h​,​ ​c​r​e​a​t​e​ ​b​a​c​k​u​p​s​,​ ​a​n​d​ ​r​e​s​t​o​r​e​ ​a​ ​p​r​e​v​i​o​u​s​ ​b​a​c​k​u​p​.
		 */
		databaseDescription: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​a​n​d​ ​b​a​c​k​u​p​s
		 */
		databaseTitle: string
		/**
		 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​b​a​c​k​u​p​?​ ​t​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		deleteBackupDescription: string
		/**
		 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​"​{​n​a​m​e​}​"​?​ ​t​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 * @param {unknown} name
		 */
		deleteBackupNamedDescription: RequiredParams<'name'>
		/**
		 * d​e​l​e​t​e​ ​b​a​c​k​u​p
		 */
		deleteBackupTitle: string
		/**
		 * m​a​n​a​g​e​ ​t​h​e​ ​e​n​d​i​n​g​-​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​,​ ​a​p​p​ ​u​p​d​a​t​e​s​,​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​,​ ​b​a​c​k​u​p​s​,​ ​a​n​d​ ​a​p​p​ ​m​e​t​a​d​a​t​a​.
		 */
		description: string
		/**
		 * d​o​w​n​l​o​a​d​i​n​g​ ​u​p​d​a​t​e
		 */
		downloadingUpdate: string
		/**
		 * c​h​o​o​s​e​ ​h​o​w​ ​m​a​n​y​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​c​o​n​t​r​a​c​t​ ​e​n​d​ ​t​h​e​ ​d​a​s​h​b​o​a​r​d​ ​s​h​o​u​l​d​ ​c​o​u​n​t​ ​a​s​ ​e​n​d​i​n​g​ ​s​o​o​n​.
		 */
		endingSoonDescription: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o
		 */
		endingSoonInvalid: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w
		 */
		endingSoonTitle: string
		/**
		 * y​o​u​'​r​e​ ​a​l​r​e​a​d​y​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​r​e​l​e​a​s​e​.
		 */
		latestRelease: string
		/**
		 * t​h​e​r​e​ ​w​a​s​ ​a​ ​p​r​o​b​l​e​m​ ​l​o​a​d​i​n​g​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​s​e​t​t​i​n​g​s​ ​s​n​a​p​s​h​o​t​.
		 */
		loadErrorDescription: string
		/**
		 * s​e​t​t​i​n​g​s​ ​a​r​e​ ​u​n​a​v​a​i​l​a​b​l​e​ ​r​i​g​h​t​ ​n​o​w
		 */
		loadErrorTitle: string
		/**
		 * p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p
		 */
		protectedUpdateBackup: string
		/**
		 * u​p​d​a​t​e​ ​v​{​v​e​r​s​i​o​n​}​ ​i​s​ ​a​v​a​i​l​a​b​l​e​.
		 * @param {unknown} version
		 */
		releaseAvailable: RequiredParams<'version'>
		/**
		 * r​e​s​t​o​r​e​ ​b​a​c​k​u​p
		 */
		restoreBackupTitle: string
		/**
		 * t​h​e​ ​u​p​d​a​t​e​ ​h​a​s​ ​b​e​e​n​ ​i​n​s​t​a​l​l​e​d​.​ ​o​n​ ​w​i​n​d​o​w​s​ ​t​h​e​ ​a​p​p​ ​m​a​y​ ​c​l​o​s​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​d​u​r​i​n​g​ ​i​n​s​t​a​l​l​a​t​i​o​n​;​ ​o​t​h​e​r​w​i​s​e​ ​r​e​s​t​a​r​t​ ​r​e​n​t​a​b​l​e​ ​t​o​ ​f​i​n​i​s​h​ ​s​w​i​t​c​h​i​n​g​ ​v​e​r​s​i​o​n​s​.
		 */
		restartNotice: string
		/**
		 * n​o​ ​b​a​c​k​u​p​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.
		 */
		noBackups: string
		/**
		 * l​e​a​v​i​n​g​ ​t​h​i​s​ ​e​m​p​t​y​ ​u​s​e​s​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​p​a​t​h​ ​a​b​o​v​e​.​ ​s​a​v​i​n​g​ ​r​e​c​o​n​n​e​c​t​s​ ​i​m​m​e​d​i​a​t​e​l​y​,​ ​a​n​d​ ​s​t​a​r​t​u​p​ ​w​i​l​l​ ​r​u​n​ ​m​i​g​r​a​t​i​o​n​s​ ​a​g​a​i​n​ ​o​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​.
		 */
		pathOverrideDescription: string
		/**
		 * l​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​u​s​e​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h
		 */
		pathOverridePlaceholder: string
		/**
		 * c​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​d​i​s​p​l​a​y​ ​l​a​n​g​u​a​g​e​.​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e​ ​w​i​l​l​ ​u​p​d​a​t​e​ ​i​m​m​e​d​i​a​t​e​l​y​.
		 */
		localeDescription: string
		/**
		 * d​i​s​p​l​a​y​ ​l​a​n​g​u​a​g​e
		 */
		localeLabel: string
		/**
		 * l​a​n​g​u​a​g​e
		 */
		localeTitle: string
		/**
		 * s​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * c​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​.​.​.
		 */
		updatesChecking: string
		/**
		 * c​h​e​c​k​ ​g​i​t​h​u​b​ ​r​e​l​e​a​s​e​s​ ​f​o​r​ ​a​ ​n​e​w​e​r​ ​s​i​g​n​e​d​ ​b​u​i​l​d​.​ ​i​f​ ​s​t​a​r​t​u​p​ ​l​a​t​e​r​ ​f​a​i​l​s​ ​a​f​t​e​r​ ​a​n​ ​u​p​d​a​t​e​,​ ​r​e​n​t​a​b​l​e​ ​w​i​l​l​ ​o​f​f​e​r​ ​r​o​l​l​b​a​c​k​ ​t​o​ ​t​h​e​ ​p​r​o​t​e​c​t​e​d​ ​p​r​e​-​u​p​d​a​t​e​ ​b​a​c​k​u​p​.
		 */
		updatesDescription: string
		/**
		 * a​p​p​ ​u​p​d​a​t​e​s
		 */
		updatesTitle: string
		/**
		 * t​h​e​ ​a​p​p​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​u​s​i​n​g​ ​a​ ​c​u​s​t​o​m​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​o​v​e​r​r​i​d​e​.
		 */
		usingCustomDatabasePath: string
		/**
		 * t​h​e​ ​a​p​p​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​u​s​i​n​g​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​d​a​t​a​b​a​s​e​ ​p​a​t​h​.
		 */
		usingDefaultDatabasePath: string
	}
	complexes: {
		hooks: {
			/**
			 * c​o​m​p​l​e​x​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * c​o​m​p​l​e​x​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * u​n​i​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitCreateSuccess: string
			/**
			 * u​n​i​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitDeleteSuccess: string
			/**
			 * u​n​i​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			unitUpdateSuccess: string
			/**
			 * c​o​m​p​l​e​x​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		form: {
			/**
			 * n​a​m​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​p​r​e​v​i​o​u​s​l​y​ ​r​e​g​i​s​t​e​r​e​d​ ​c​o​m​p​l​e​x​.
			 */
			duplicateName: string
		}
		units: {
			/**
			 * n​a​m​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​u​n​i​t​ ​i​n​ ​t​h​e​ ​s​a​m​e​ ​c​o​m​p​l​e​x​.
			 */
			duplicateName: string
			/**
			 * u​n​i​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			management: string
		}
	}
	tenants: {
		hooks: {
			/**
			 * t​e​n​a​n​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * t​e​n​a​n​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * t​e​n​a​n​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		form: {
			/**
			 * n​a​t​i​o​n​a​l​ ​i​d​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​r​e​g​i​s​t​e​r​e​d​ ​t​e​n​a​n​t​.
			 */
			duplicateNationalId: string
			/**
			 * p​h​o​n​e​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​ ​r​e​g​i​s​t​e​r​e​d​ ​t​e​n​a​n​t​.
			 */
			duplicatePhone: string
			/**
			 * i​q​a​m​a​ ​m​u​s​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​1​ ​o​r​ ​2​ ​a​n​d​ ​b​e​ ​1​0​ ​d​i​g​i​t​s​ ​l​o​n​g​.
			 */
			invalidNationalId: string
			/**
			 * p​h​o​n​e​ ​m​u​s​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​+​9​6​6​ ​a​n​d​ ​b​e​ ​1​0​ ​d​i​g​i​t​s​ ​l​o​n​g​.
			 */
			invalidPhone: string
			/**
			 * p​h​o​n​e​ ​(​+​9​6​6​.​.​.​)
			 */
			phonePlaceholder: string
		}
	}
	contracts: {
		form: {
			/**
			 * s​t​a​r​t​ ​d​a​t​e
			 */
			startDate: string
			/**
			 * e​n​d​ ​d​a​t​e
			 */
			calculatedEndDate: string
			/**
			 * u​p​d​a​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​f​r​o​m​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​y​c​l​e​,​ ​s​t​a​r​t​ ​d​a​t​e​,​ ​a​n​d​ ​n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​.
			 */
			calculatedEndDateHint: string
			/**
			 * c​o​s​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			costGreaterThanZero: string
			/**
			 * c​o​s​t​ ​p​e​r​ ​p​a​y​m​e​n​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			costPerPaymentGreaterThanZero: string
			/**
			 * c​o​s​t​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			costRequired: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o​.
			 */
			cyclesGreaterThanZero: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			cyclesRequired: string
			/**
			 * g​o​v​e​r​n​m​e​n​t​ ​i​d​ ​i​s​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​a​n​o​t​h​e​r​ ​c​o​n​t​r​a​c​t​.
			 */
			duplicateGovernmentId: string
			/**
			 * e​n​d​ ​d​a​t​e​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​s​t​a​r​t​ ​d​a​t​e​.
			 */
			endDateAfterStart: string
			/**
			 * e​n​d​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			endDateRequired: string
			/**
			 * e​n​d​ ​d​a​t​e
			 */
			endDateShort: string
			/**
			 * p​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​v​a​l​i​d​ ​t​e​n​a​n​t​.
			 */
			invalidTenant: string
			/**
			 * l​o​a​d​i​n​g​ ​t​e​n​a​n​t​.​.​.
			 */
			loadingTenant: string
			/**
			 * l​o​a​d​i​n​g​ ​t​e​n​a​n​t​s​.​.​.
			 */
			loadingTenants: string
			/**
			 * n​o​ ​t​e​n​a​n​t​ ​f​o​u​n​d​.
			 */
			noTenantFound: string
			/**
			 * n​u​m​b​e​r​ ​o​f​ ​c​y​c​l​e​s
			 */
			numberOfCycles: string
			/**
			 * p​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​m​u​s​t​ ​b​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​z​e​r​o
			 */
			paymentAmountGreaterThanZero: string
			/**
			 * p​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			paymentAmountRequired: string
			/**
			 * p​a​y​m​e​n​t​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			paymentDateRequired: string
			/**
			 * p​i​c​k​ ​a​ ​d​a​t​e
			 */
			pickDate: string
			/**
			 * p​i​c​k​ ​a​ ​d​a​t​e​ ​r​a​n​g​e
			 */
			pickDateRange: string
			/**
			 * c​o​n​t​r​a​c​t​ ​p​e​r​i​o​d​ ​m​u​s​t​ ​b​e​ ​a​ ​w​h​o​l​e​ ​n​u​m​b​e​r​ ​o​f​ ​{​d​a​y​s​}​-​d​a​y​ ​{​i​n​t​e​r​v​a​l​}​ ​c​y​c​l​e​s​.
			 * @param {unknown} days
			 * @param {unknown} interval
			 */
			periodMustMatchWholeCycles: RequiredParams<'days' | 'interval'>
			/**
			 * s​e​a​r​c​h​ ​a​n​d​ ​s​e​l​e​c​t​ ​t​e​n​a​n​t
			 */
			searchAndSelectTenant: string
			/**
			 * s​e​a​r​c​h​ ​t​e​n​a​n​t​ ​b​y​ ​n​a​m​e​,​ ​i​d​ ​o​r​ ​p​h​o​n​e​.​.​.
			 */
			searchTenantPlaceholder: string
			/**
			 * s​t​a​r​t​ ​d​a​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			startDateRequired: string
			/**
			 * s​t​a​r​t​ ​t​y​p​i​n​g​ ​t​o​ ​s​e​a​r​c​h​ ​t​e​n​a​n​t​s​ ​b​y​ ​n​a​m​e​,​ ​i​d​ ​o​r​ ​p​h​o​n​e​.
			 */
			startTypingTenantSearch: string
			/**
			 * t​e​n​a​n​t​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			tenantRequired: string
		}
		hooks: {
			/**
			 * u​n​i​t​s​ ​a​d​d​e​d​ ​t​o​ ​c​o​n​t​r​a​c​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			assignUnitsSuccess: string
			/**
			 * p​a​y​m​e​n​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createPaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			createSuccess: string
			/**
			 * p​a​y​m​e​n​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deletePaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			deleteSuccess: string
			/**
			 * u​n​i​t​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​c​o​n​t​r​a​c​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			removeUnitSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			restoreSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​t​e​r​m​i​n​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			terminateSuccess: string
			/**
			 * p​a​y​m​e​n​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updatePaymentSuccess: string
			/**
			 * c​o​n​t​r​a​c​t​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			updateSuccess: string
		}
		intervals: {
			/**
			 * a​n​n​u​a​l
			 */
			annual: string
			/**
			 * m​o​n​t​h​l​y
			 */
			monthly: string
			/**
			 * q​u​a​r​t​e​r​l​y
			 */
			quarterly: string
			/**
			 * s​e​m​i​-​a​n​n​u​a​l
			 */
			semiAnnual: string
		}
		payments: {
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​r​e​a​c​h​e​d​ ​i​t​s​ ​r​e​q​u​i​r​e​d​ ​t​o​t​a​l​ ​p​a​y​m​e​n​t​ ​a​m​o​u​n​t​.​ ​y​o​u​ ​c​a​n​ ​s​t​i​l​l​ ​e​d​i​t​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​ ​i​f​ ​n​e​e​d​e​d​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​ ​m​o​r​e​ ​u​n​t​i​l​ ​t​h​e​ ​p​a​i​d​ ​t​o​t​a​l​ ​d​r​o​p​s​ ​b​e​l​o​w​ ​t​h​e​ ​r​e​q​u​i​r​e​d​ ​a​m​o​u​n​t​.
			 */
			fullyPaidNotice: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​h​a​s​ ​b​e​e​n​ ​f​u​l​l​y​ ​p​a​i​d​.​ ​y​o​u​ ​c​a​n​ ​e​d​i​t​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​ ​m​o​r​e​.
			 */
			fullyPaidSummary: string
			/**
			 * {​p​e​r​c​e​n​t​}​%​ ​f​u​l​f​i​l​l​e​d
			 * @param {unknown} percent
			 */
			percentFulfilled: RequiredParams<'percent'>
			/**
			 * {​a​m​o​u​n​t​}​ ​s​a​r​ ​r​e​m​a​i​n​i​n​g
			 * @param {unknown} amount
			 */
			remaining: RequiredParams<'amount'>
			/**
			 * t​e​r​m​i​n​a​t​e​d​ ​c​o​n​t​r​a​c​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​p​a​y​m​e​n​t​ ​h​i​s​t​o​r​y​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​d​d​,​ ​e​d​i​t​,​ ​o​r​ ​d​e​l​e​t​e​ ​p​a​y​m​e​n​t​s​ ​u​n​t​i​l​ ​t​h​e​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​u​n​t​e​r​m​i​n​a​t​e​d​.
			 */
			terminatedNotice: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​t​e​r​m​i​n​a​t​e​d​ ​a​n​d​ ​l​o​c​k​e​d​.​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d​s​ ​a​r​e​ ​r​e​a​d​-​o​n​l​y​.
			 */
			terminatedSummary: string
			/**
			 * p​a​y​m​e​n​t​s
			 */
			title: string
			/**
			 * p​a​y​m​e​n​t​s​ ​f​o​r​ ​{​g​o​v​I​d​}
			 * @param {unknown} govId
			 */
			titleFor: RequiredParams<'govId'>
			/**
			 * t​r​a​c​k​ ​c​o​n​t​r​a​c​t​ ​p​a​y​m​e​n​t​s​ ​a​n​d​ ​a​d​d​ ​n​e​w​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d​s​ ​h​e​r​e​.
			 */
			trackSummary: string
		}
		statusDescriptions: {
			/**
			 * a​c​t​i​v​e​;​ ​p​a​y​m​e​n​t​s​ ​o​n​ ​t​r​a​c​k
			 */
			active: string
			/**
			 * e​n​d​e​d​;​ ​n​o​t​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			defaulted: string
			/**
			 * e​n​d​e​d​;​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			expired: string
			/**
			 * a​c​t​i​v​e​;​ ​p​a​i​d​ ​i​n​ ​f​u​l​l
			 */
			fulfilled: string
			/**
			 * s​c​h​e​d​u​l​e​d​;​ ​s​t​a​r​t​s​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e
			 */
			scheduled: string
			/**
			 * m​a​n​u​a​l​l​y​ ​t​e​r​m​i​n​a​t​e​d​;​ ​l​o​c​k​e​d​ ​f​o​r​ ​c​h​a​n​g​e​s
			 */
			terminated: string
		}
		table: {
			/**
			 * p​a​y​m​e​n​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			paymentsManagement: string
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​e​ ​m​a​n​u​a​l​ ​t​e​r​m​i​n​a​t​i​o​n​ ​f​r​o​m​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​?
			 */
			restoreDescription: string
			/**
			 * r​e​s​t​o​r​e​ ​c​o​n​t​r​a​c​t
			 */
			restoreTitle: string
			/**
			 * a​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​m​a​n​u​a​l​l​y​ ​t​e​r​m​i​n​a​t​e​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​?​ ​t​h​i​s​ ​o​n​l​y​ ​w​o​r​k​s​ ​f​o​r​ ​a​c​t​i​v​e​ ​o​r​ ​p​a​s​t​ ​c​o​n​t​r​a​c​t​s​.
			 */
			terminateDescription: string
			/**
			 * t​e​r​m​i​n​a​t​e​ ​c​o​n​t​r​a​c​t
			 */
			terminateTitle: string
			/**
			 * t​e​n​a​n​t​ ​#​{​t​e​n​a​n​t​I​d​}
			 * @param {unknown} tenantId
			 */
			tenantFallback: RequiredParams<'tenantId'>
			/**
			 * u​n​i​t​s​ ​m​a​n​a​g​e​m​e​n​t
			 */
			unitsManagement: string
		}
		units: {
			/**
			 * r​e​m​o​v​e​ ​a​ ​u​n​i​t​ ​f​r​o​m​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​w​h​e​n​ ​i​t​ ​s​h​o​u​l​d​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​l​i​n​k​e​d​ ​t​o​ ​i​t​.
			 */
			assignedDescriptionEditable: string
			/**
			 * r​e​v​i​e​w​ ​t​h​e​ ​u​n​i​t​s​ ​c​u​r​r​e​n​t​l​y​ ​l​i​n​k​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​.
			 */
			assignedDescriptionLocked: string
			/**
			 * a​s​s​i​g​n​e​d​ ​u​n​i​t​s
			 */
			assignedTitle: string
			/**
			 * c​h​o​o​s​e​ ​a​ ​c​o​m​p​l​e​x​ ​t​o​ ​s​h​o​w​ ​u​n​i​t​s​ ​t​h​a​t​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​t​i​m​e​f​r​a​m​e​.​ ​u​n​i​t​s​ ​l​i​n​k​e​d​ ​t​o​ ​o​v​e​r​l​a​p​p​i​n​g​ ​c​o​n​t​r​a​c​t​s​ ​a​r​e​ ​e​x​c​l​u​d​e​d​.
			 */
			availableDescription: string
			/**
			 * a​v​a​i​l​a​b​l​e​ ​u​n​i​t​s
			 */
			availableTitle: string
			/**
			 * l​o​a​d​i​n​g​ ​c​o​n​t​r​a​c​t​.​.​.
			 */
			loadingContract: string
			/**
			 * c​o​n​t​r​a​c​t​s​ ​w​i​t​h​ ​r​e​g​i​s​t​e​r​e​d​ ​p​a​y​m​e​n​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​l​i​n​k​e​d​ ​u​n​i​t​s​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​s​s​i​g​n​ ​o​r​ ​r​e​m​o​v​e​ ​u​n​i​t​s​ ​a​f​t​e​r​ ​p​a​y​m​e​n​t​s​ ​h​a​v​e​ ​b​e​e​n​ ​r​e​c​o​r​d​e​d​.
			 */
			lockNoticeHasPayments: string
			/**
			 * t​e​r​m​i​n​a​t​e​d​ ​c​o​n​t​r​a​c​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.​ ​y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​l​i​n​k​e​d​ ​u​n​i​t​s​ ​h​e​r​e​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​n​o​t​ ​a​s​s​i​g​n​ ​o​r​ ​r​e​m​o​v​e​ ​u​n​i​t​s​ ​u​n​t​i​l​ ​t​h​e​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​u​n​t​e​r​m​i​n​a​t​e​d​.
			 */
			lockNoticeTerminated: string
			/**
			 * a​s​s​i​g​n​ ​a​v​a​i​l​a​b​l​e​ ​u​n​i​t​s​ ​b​y​ ​c​o​m​p​l​e​x​,​ ​t​h​e​n​ ​m​a​n​a​g​e​ ​t​h​e​ ​u​n​i​t​s​ ​a​l​r​e​a​d​y​ ​l​i​n​k​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​.
			 */
			lockSummaryDefault: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​h​a​s​ ​r​e​g​i​s​t​e​r​e​d​ ​p​a​y​m​e​n​t​s​.​ ​u​n​i​t​ ​a​s​s​i​g​n​m​e​n​t​s​ ​a​r​e​ ​l​o​c​k​e​d​.
			 */
			lockSummaryHasPayments: string
			/**
			 * t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​i​s​ ​t​e​r​m​i​n​a​t​e​d​ ​a​n​d​ ​l​o​c​k​e​d​.​ ​u​n​i​t​ ​a​s​s​i​g​n​m​e​n​t​s​ ​a​r​e​ ​r​e​a​d​-​o​n​l​y​.
			 */
			lockSummaryTerminated: string
			/**
			 * n​o​ ​u​n​i​t​s​ ​a​r​e​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​y​e​t​.
			 */
			noAssignedUnits: string
			/**
			 * n​o​ ​u​n​i​t​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​t​h​i​s​ ​c​o​n​t​r​a​c​t​ ​t​i​m​e​f​r​a​m​e​ ​i​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​o​m​p​l​e​x​.
			 */
			noAvailableUnits: string
			/**
			 * s​e​l​e​c​t​ ​a​ ​c​o​m​p​l​e​x​ ​t​o​ ​l​o​a​d​ ​a​v​a​i​l​a​b​l​e​ ​u​n​i​t​s​.
			 */
			selectComplex: string
			/**
			 * s​e​l​e​c​t​ ​c​o​m​p​l​e​x
			 */
			selectComplexPlaceholder: string
			/**
			 * u​n​i​t​s​ ​f​o​r​ ​{​g​o​v​I​d​}
			 * @param {unknown} govId
			 */
			unitsFor: RequiredParams<'govId'>
			/**
			 * u​n​i​t​s
			 */
			unitsTitle: string
		}
	}
	settingsHooks: {
		/**
		 * b​a​c​k​u​p​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupCreated: string
		/**
		 * b​a​c​k​u​p​ ​d​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupDeleted: string
		/**
		 * b​a​c​k​u​p​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		backupRestored: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​r​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		databasePathReset: string
		/**
		 * d​a​t​a​b​a​s​e​ ​p​a​t​h​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		databasePathUpdated: string
		/**
		 * e​n​d​i​n​g​ ​s​o​o​n​ ​n​o​t​i​c​e​ ​w​i​n​d​o​w​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		endingSoonUpdated: string
		/**
		 * p​r​o​t​e​c​t​e​d​ ​u​p​d​a​t​e​ ​b​a​c​k​u​p​ ​r​e​s​t​o​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
		 */
		rollbackRestored: string
		/**
		 * s​t​a​r​t​u​p​ ​r​e​c​o​v​e​r​y​ ​c​l​e​a​r​e​d​.​ ​r​e​t​r​y​i​n​g​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​v​e​r​s​i​o​n​ ​i​s​ ​n​o​w​ ​a​l​l​o​w​e​d​.
		 */
		startupRecoveryCleared: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * rentable
		 */
		name: () => LocalizedString
	}
	common: {
		actions: {
			/**
			 * actions
			 */
			actions: () => LocalizedString
			/**
			 * assign selected
			 */
			assignSelected: () => LocalizedString
			/**
			 * assigning...
			 */
			assigning: () => LocalizedString
			/**
			 * cancel
			 */
			cancel: () => LocalizedString
			/**
			 * check for updates
			 */
			checkForUpdates: () => LocalizedString
			/**
			 * checking for updates...
			 */
			checkingForUpdates: () => LocalizedString
			/**
			 * create
			 */
			create: () => LocalizedString
			/**
			 * create backup
			 */
			createBackup: () => LocalizedString
			/**
			 * creating...
			 */
			creating: () => LocalizedString
			/**
			 * creating backup...
			 */
			creatingBackup: () => LocalizedString
			/**
			 * customize columns
			 */
			customizeColumns: () => LocalizedString
			/**
			 * delete
			 */
			'delete': () => LocalizedString
			/**
			 * deleting...
			 */
			deleting: () => LocalizedString
			/**
			 * drag to reorder
			 */
			dragToReorder: () => LocalizedString
			/**
			 * download & install
			 */
			downloadAndInstall: () => LocalizedString
			/**
			 * edit
			 */
			edit: () => LocalizedString
			/**
			 * installing update...
			 */
			installingUpdate: () => LocalizedString
			/**
			 * new record
			 */
			newRecord: () => LocalizedString
			/**
			 * open menu
			 */
			openMenu: () => LocalizedString
			/**
			 * open payments
			 */
			openPayments: () => LocalizedString
			/**
			 * open previous release
			 */
			openPreviousRelease: () => LocalizedString
			/**
			 * proceed
			 */
			proceed: () => LocalizedString
			/**
			 * remove
			 */
			remove: () => LocalizedString
			/**
			 * restore
			 */
			restore: () => LocalizedString
			/**
			 * restoring...
			 */
			restoring: () => LocalizedString
			/**
			 * restart app
			 */
			restartApp: () => LocalizedString
			/**
			 * retry
			 */
			retry: () => LocalizedString
			/**
			 * retry startup
			 */
			retryStartup: () => LocalizedString
			/**
			 * rollback
			 */
			rollback: () => LocalizedString
			/**
			 * rolling back...
			 */
			rollingBack: () => LocalizedString
			/**
			 * save
			 */
			save: () => LocalizedString
			/**
			 * save database path
			 */
			saveDatabasePath: () => LocalizedString
			/**
			 * save window
			 */
			saveWindow: () => LocalizedString
			/**
			 * saving...
			 */
			saving: () => LocalizedString
			/**
			 * terminate
			 */
			terminate: () => LocalizedString
			/**
			 * terminating...
			 */
			terminating: () => LocalizedString
			/**
			 * unterminate
			 */
			unterminate: () => LocalizedString
			/**
			 * update
			 */
			update: () => LocalizedString
			/**
			 * use default path
			 */
			useDefaultPath: () => LocalizedString
			/**
			 * working...
			 */
			working: () => LocalizedString
		}
		labels: {
			/**
			 * action
			 */
			action: () => LocalizedString
			/**
			 * amount
			 */
			amount: () => LocalizedString
			/**
			 * app version
			 */
			appVersion: () => LocalizedString
			/**
			 * available version
			 */
			availableVersion: () => LocalizedString
			/**
			 * backup count
			 */
			backupCount: () => LocalizedString
			/**
			 * complex
			 */
			complex: () => LocalizedString
			/**
			 * contract ends
			 */
			contractEnds: () => LocalizedString
			/**
			 * contract period
			 */
			contractPeriod: () => LocalizedString
			/**
			 * cost per payment
			 */
			costPerPayment: () => LocalizedString
			/**
			 * current database path
			 */
			currentDatabasePath: () => LocalizedString
			/**
			 * current value
			 */
			currentValue: () => LocalizedString
			/**
			 * current version
			 */
			currentVersion: () => LocalizedString
			/**
			 * custom database path override
			 */
			customDatabasePathOverride: () => LocalizedString
			/**
			 * cycle
			 */
			cycle: () => LocalizedString
			/**
			 * default database path
			 */
			defaultDatabasePath: () => LocalizedString
			/**
			 * due balance
			 */
			dueBalance: () => LocalizedString
			/**
			 * due balance covered to date
			 */
			dueBalanceCoveredToDate: () => LocalizedString
			/**
			 * end
			 */
			end: () => LocalizedString
			/**
			 * government id
			 */
			governmentId: () => LocalizedString
			/**
			 * government id (optional)
			 */
			governmentIdOptional: () => LocalizedString
			/**
			 * last backup time
			 */
			lastBackupTime: () => LocalizedString
			/**
			 * last sync time
			 */
			lastSyncTime: () => LocalizedString
			/**
			 * location
			 */
			location: () => LocalizedString
			/**
			 * name
			 */
			name: () => LocalizedString
			/**
			 * national id
			 */
			nationalId: () => LocalizedString
			/**
			 * notice window (days)
			 */
			noticeWindowDays: () => LocalizedString
			/**
			 * payment
			 */
			payment: () => LocalizedString
			/**
			 * payment date
			 */
			paymentDate: () => LocalizedString
			/**
			 * payment fulfillment
			 */
			paymentFulfillment: () => LocalizedString
			/**
			 * phone
			 */
			phone: () => LocalizedString
			/**
			 * release date
			 */
			releaseDate: () => LocalizedString
			/**
			 * release notes
			 */
			releaseNotes: () => LocalizedString
			/**
			 * remaining due balance
			 */
			remainingDueBalance: () => LocalizedString
			/**
			 * start
			 */
			start: () => LocalizedString
			/**
			 * status
			 */
			status: () => LocalizedString
			/**
			 * tenant
			 */
			tenant: () => LocalizedString
			/**
			 * unit
			 */
			unit: () => LocalizedString
			/**
			 * units
			 */
			units: () => LocalizedString
		}
		messages: {
			/**
			 * loading app...
			 */
			loadingApp: () => LocalizedString
			/**
			 * loading complexes...
			 */
			loadingComplexes: () => LocalizedString
			/**
			 * loading dashboard...
			 */
			loadingDashboard: () => LocalizedString
			/**
			 * loading settings...
			 */
			loadingSettings: () => LocalizedString
			/**
			 * never
			 */
			never: () => LocalizedString
			/**
			 * no results.
			 */
			noResults: () => LocalizedString
			/**
			 * sar
			 */
			sar: () => LocalizedString
			/**
			 * unexpected error occurred!
			 */
			unexpectedError: () => LocalizedString
			/**
			 * unknown
			 */
			unknown: () => LocalizedString
		}
		nav: {
			/**
			 * complexes
			 */
			complexes: () => LocalizedString
			/**
			 * contracts
			 */
			contracts: () => LocalizedString
			/**
			 * dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * payments
			 */
			payments: () => LocalizedString
			/**
			 * primary
			 */
			primary: () => LocalizedString
			/**
			 * settings
			 */
			settings: () => LocalizedString
			/**
			 * tenants
			 */
			tenants: () => LocalizedString
			/**
			 * units
			 */
			units: () => LocalizedString
		}
		status: {
			/**
			 * active
			 */
			active: () => LocalizedString
			/**
			 * defaulted
			 */
			defaulted: () => LocalizedString
			/**
			 * expired
			 */
			expired: () => LocalizedString
			/**
			 * fulfilled
			 */
			fulfilled: () => LocalizedString
			/**
			 * occupied
			 */
			occupied: () => LocalizedString
			/**
			 * overdue
			 */
			overdue: () => LocalizedString
			/**
			 * scheduled
			 */
			scheduled: () => LocalizedString
			/**
			 * terminated
			 */
			terminated: () => LocalizedString
			/**
			 * vacant
			 */
			vacant: () => LocalizedString
		}
		table: {
			/**
			 * go to first page
			 */
			goToFirstPage: () => LocalizedString
			/**
			 * go to last page
			 */
			goToLastPage: () => LocalizedString
			/**
			 * go to next page
			 */
			goToNextPage: () => LocalizedString
			/**
			 * go to previous page
			 */
			goToPreviousPage: () => LocalizedString
			/**
			 * page {page} of {count}
			 */
			pageOf: (arg: { count: unknown, page: unknown }) => LocalizedString
			/**
			 * rows per page
			 */
			rowsPerPage: () => LocalizedString
			/**
			 * {selected} of {total} row(s) selected.
			 */
			rowsSelected: (arg: { selected: unknown, total: unknown }) => LocalizedString
			/**
			 * search...
			 */
			searchPlaceholder: () => LocalizedString
		}
		time: {
			/**
			 * {count} day
			 */
			day: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count} days
			 */
			days: (arg: { count: unknown }) => LocalizedString
		}
		window: {
			/**
			 * close window
			 */
			close: () => LocalizedString
			/**
			 * minimize window
			 */
			minimize: () => LocalizedString
			/**
			 * toggle maximize window
			 */
			toggleMaximize: () => LocalizedString
		}
		ui: {
			/**
			 * breadcrumb
			 */
			breadcrumb: () => LocalizedString
			/**
			 * close
			 */
			close: () => LocalizedString
			/**
			 * command palette
			 */
			commandPalette: () => LocalizedString
			/**
			 * search for a command to run
			 */
			commandPaletteDescription: () => LocalizedString
			/**
			 * loading
			 */
			loading: () => LocalizedString
			/**
			 * displays the mobile sidebar.
			 */
			mobileSidebarDescription: () => LocalizedString
			/**
			 * more
			 */
			more: () => LocalizedString
			/**
			 * more pages
			 */
			morePages: () => LocalizedString
			/**
			 * next
			 */
			next: () => LocalizedString
			/**
			 * next slide
			 */
			nextSlide: () => LocalizedString
			/**
			 * pagination
			 */
			pagination: () => LocalizedString
			/**
			 * previous
			 */
			previous: () => LocalizedString
			/**
			 * previous slide
			 */
			previousSlide: () => LocalizedString
			/**
			 * sidebar
			 */
			sidebar: () => LocalizedString
			/**
			 * toggle sidebar
			 */
			toggleSidebar: () => LocalizedString
		}
		deleteDialog: {
			/**
			 * are you sure you want to delete this record(s)?
			 */
			description: () => LocalizedString
			/**
			 * confirmation
			 */
			title: () => LocalizedString
		}
	}
	layout: {
		startup: {
			/**
			 * there was a problem connecting the database or running startup sync.
			 */
			failedToStartDescription: () => LocalizedString
			/**
			 * failed to start the app.
			 */
			failedToStartFallback: () => LocalizedString
			/**
			 * failed to start the app
			 */
			failedToStartTitle: () => LocalizedString
			/**
			 * previous version
			 */
			previousVersion: () => LocalizedString
			/**
			 * rentable detected update recovery while starting v{version}. retry startup, or open the previous release if you need to reinstall it.
			 */
			recoveryDescription: (arg: { version: unknown }) => LocalizedString
			/**
			 * the protected backup was created from v{backupVersion}. if startup still fails, reinstall the previous release before opening rentable again.
			 */
			recoveryDetails: (arg: { backupVersion: unknown }) => LocalizedString
			/**
			 * update recovery required
			 */
			recoveryRequiredTitle: () => LocalizedString
			/**
			 * rollback completed but the recovery snapshot was not updated.
			 */
			recoverySnapshotNotUpdated: () => LocalizedString
			/**
			 * restored backup
			 */
			restoredBackup: () => LocalizedString
			/**
			 * the protected database backup has been restored and the app is locked until you reinstall the previous release.
			 */
			rolledBackDescription: () => LocalizedString
			/**
			 * open the previous github release, reinstall it, then launch rentable again.
			 */
			rolledBackDetails: () => LocalizedString
			/**
			 * update rolled back
			 */
			rolledBackTitle: () => LocalizedString
			/**
			 * backup
			 */
			startupRecoveryBackup: () => LocalizedString
		}
	}
	dashboard: {
		/**
		 * track contract health, payment performance, and occupancy after status synchronization.
		 */
		description: () => LocalizedString
		followUps: {
			/**
			 * {count} open follow-up
			 */
			countOne: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count} open follow-ups
			 */
			countOther: (arg: { count: unknown }) => LocalizedString
			/**
			 * contracts with a scheduled due on or before today this month, or an overdue defaulted balance that still needs follow-up.
			 */
			description: () => LocalizedString
			/**
			 * no payment follow-up is needed right now.
			 */
			empty: () => LocalizedString
			/**
			 * {percent}% of the due balance covered to date
			 */
			progressSummary: (arg: { percent: unknown }) => LocalizedString
			/**
			 * {amount} sar remaining
			 */
			remaining: (arg: { amount: unknown }) => LocalizedString
			/**
			 * payments requiring follow-up in {monthLabel}
			 */
			title: (arg: { monthLabel: unknown }) => LocalizedString
			/**
			 * dashboard data is unavailable right now.
			 */
			unavailable: () => LocalizedString
		}
		/**
		 * last synchronized {value}
		 */
		lastSynchronized: (arg: { value: unknown }) => LocalizedString
		sections: {
			contracts: {
				/**
				 * status health across the current portfolio, with ending soon based on the configured {noticeWindow} notice window.
				 */
				description: (arg: { noticeWindow: unknown }) => LocalizedString
				/**
				 * {active} active • {endingSoon} ending within {noticeWindow}
				 */
				heroHint: (arg: { active: unknown, endingSoon: unknown, noticeWindow: unknown }) => LocalizedString
				/**
				 * current portfolio size
				 */
				heroLabel: () => LocalizedString
				/**
				 * contracts
				 */
				title: () => LocalizedString
			}
			money: {
				/**
				 * scheduled dues for {monthLabel}, payments received this month, and overall contract balances.
				 */
				description: (arg: { monthLabel: unknown }) => LocalizedString
				/**
				 * {rate}% of the due for {monthLabel} is covered
				 */
				heroHint: (arg: { monthLabel: unknown, rate: unknown }) => LocalizedString
				/**
				 * outstanding now
				 */
				heroLabel: () => LocalizedString
				/**
				 * money
				 */
				title: () => LocalizedString
			}
			occupancy: {
				/**
				 * stored unit statuses after dashboard synchronization.
				 */
				description: () => LocalizedString
				/**
				 * {occupied} occupied out of {total} units
				 */
				heroHint: (arg: { occupied: unknown, total: unknown }) => LocalizedString
				/**
				 * occupancy rate
				 */
				heroLabel: () => LocalizedString
				/**
				 * occupancy
				 */
				title: () => LocalizedString
			}
		}
		stats: {
			/**
			 * {active} active • {endingSoon} ending within {noticeWindow}
			 */
			activeEndingWithin: (arg: { active: unknown, endingSoon: unknown, noticeWindow: unknown }) => LocalizedString
			/**
			 * due this month
			 */
			dueThisMonth: () => LocalizedString
			/**
			 * occupancy rate
			 */
			occupancyRate: () => LocalizedString
			/**
			 * overall collection rate
			 */
			overallCollectionRate: () => LocalizedString
			/**
			 * occupied units
			 */
			occupiedUnits: () => LocalizedString
			/**
			 * received this month
			 */
			receivedThisMonth: () => LocalizedString
			/**
			 * still due this month
			 */
			stillDueThisMonth: () => LocalizedString
			/**
			 * total expected amount
			 */
			totalExpectedAmount: () => LocalizedString
			/**
			 * total units
			 */
			totalUnits: () => LocalizedString
			/**
			 * vacancy rate
			 */
			vacancyRate: () => LocalizedString
			/**
			 * vacant units
			 */
			vacantUnits: () => LocalizedString
		}
		/**
		 * dashboard
		 */
		title: () => LocalizedString
	}
	settings: {
		/**
		 * current app metadata and recent sync/backup timestamps.
		 */
		aboutDescription: () => LocalizedString
		/**
		 * about
		 */
		aboutTitle: () => LocalizedString
		/**
		 * created {value}
		 */
		createdAt: (arg: { value: unknown }) => LocalizedString
		/**
		 * backups are stored in the app backup directory and can be restored below. protected update backups are created automatically before app migrations.
		 */
		createBackupDescription: () => LocalizedString
		/**
		 * create backup
		 */
		createBackupTitle: () => LocalizedString
		/**
		 * switch the active database, fall back to the default path, create backups, and restore a previous backup.
		 */
		databaseDescription: () => LocalizedString
		/**
		 * database path and backups
		 */
		databaseTitle: () => LocalizedString
		/**
		 * are you sure you want to delete this backup? this cannot be undone.
		 */
		deleteBackupDescription: () => LocalizedString
		/**
		 * are you sure you want to delete "{name}"? this cannot be undone.
		 */
		deleteBackupNamedDescription: (arg: { name: unknown }) => LocalizedString
		/**
		 * delete backup
		 */
		deleteBackupTitle: () => LocalizedString
		/**
		 * manage the ending-soon notice window, app updates, database path, backups, and app metadata.
		 */
		description: () => LocalizedString
		/**
		 * downloading update
		 */
		downloadingUpdate: () => LocalizedString
		/**
		 * choose how many days before contract end the dashboard should count as ending soon.
		 */
		endingSoonDescription: () => LocalizedString
		/**
		 * ending soon notice window must be greater than zero
		 */
		endingSoonInvalid: () => LocalizedString
		/**
		 * ending soon notice window
		 */
		endingSoonTitle: () => LocalizedString
		/**
		 * you're already on the latest release.
		 */
		latestRelease: () => LocalizedString
		/**
		 * there was a problem loading the current settings snapshot.
		 */
		loadErrorDescription: () => LocalizedString
		/**
		 * settings are unavailable right now
		 */
		loadErrorTitle: () => LocalizedString
		/**
		 * protected update backup
		 */
		protectedUpdateBackup: () => LocalizedString
		/**
		 * update v{version} is available.
		 */
		releaseAvailable: (arg: { version: unknown }) => LocalizedString
		/**
		 * restore backup
		 */
		restoreBackupTitle: () => LocalizedString
		/**
		 * the update has been installed. on windows the app may close automatically during installation; otherwise restart rentable to finish switching versions.
		 */
		restartNotice: () => LocalizedString
		/**
		 * no backups are available yet.
		 */
		noBackups: () => LocalizedString
		/**
		 * leaving this empty uses the default path above. saving reconnects immediately, and startup will run migrations again on the selected database path.
		 */
		pathOverrideDescription: () => LocalizedString
		/**
		 * leave empty to use the default database path
		 */
		pathOverridePlaceholder: () => LocalizedString
		/**
		 * choose your preferred display language. the interface will update immediately.
		 */
		localeDescription: () => LocalizedString
		/**
		 * display language
		 */
		localeLabel: () => LocalizedString
		/**
		 * language
		 */
		localeTitle: () => LocalizedString
		/**
		 * settings
		 */
		title: () => LocalizedString
		/**
		 * checking for update...
		 */
		updatesChecking: () => LocalizedString
		/**
		 * check github releases for a newer signed build. if startup later fails after an update, rentable will offer rollback to the protected pre-update backup.
		 */
		updatesDescription: () => LocalizedString
		/**
		 * app updates
		 */
		updatesTitle: () => LocalizedString
		/**
		 * the app is currently using a custom database path override.
		 */
		usingCustomDatabasePath: () => LocalizedString
		/**
		 * the app is currently using the default database path.
		 */
		usingDefaultDatabasePath: () => LocalizedString
	}
	complexes: {
		hooks: {
			/**
			 * complex created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * complex deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * unit created successfully!
			 */
			unitCreateSuccess: () => LocalizedString
			/**
			 * unit deleted successfully!
			 */
			unitDeleteSuccess: () => LocalizedString
			/**
			 * unit updated successfully!
			 */
			unitUpdateSuccess: () => LocalizedString
			/**
			 * complex updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		form: {
			/**
			 * name is associated with a previously registered complex.
			 */
			duplicateName: () => LocalizedString
		}
		units: {
			/**
			 * name is associated with a unit in the same complex.
			 */
			duplicateName: () => LocalizedString
			/**
			 * units management
			 */
			management: () => LocalizedString
		}
	}
	tenants: {
		hooks: {
			/**
			 * tenant created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * tenant deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * tenant updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		form: {
			/**
			 * national id is associated with a registered tenant.
			 */
			duplicateNationalId: () => LocalizedString
			/**
			 * phone is associated with a registered tenant.
			 */
			duplicatePhone: () => LocalizedString
			/**
			 * iqama must start with 1 or 2 and be 10 digits long.
			 */
			invalidNationalId: () => LocalizedString
			/**
			 * phone must start with +966 and be 10 digits long.
			 */
			invalidPhone: () => LocalizedString
			/**
			 * phone (+966...)
			 */
			phonePlaceholder: () => LocalizedString
		}
	}
	contracts: {
		form: {
			/**
			 * start date
			 */
			startDate: () => LocalizedString
			/**
			 * end date
			 */
			calculatedEndDate: () => LocalizedString
			/**
			 * updated automatically from the selected cycle, start date, and number of cycles.
			 */
			calculatedEndDateHint: () => LocalizedString
			/**
			 * cost must be greater than zero.
			 */
			costGreaterThanZero: () => LocalizedString
			/**
			 * cost per payment must be greater than zero.
			 */
			costPerPaymentGreaterThanZero: () => LocalizedString
			/**
			 * cost is required.
			 */
			costRequired: () => LocalizedString
			/**
			 * number of cycles must be greater than zero.
			 */
			cyclesGreaterThanZero: () => LocalizedString
			/**
			 * number of cycles is required.
			 */
			cyclesRequired: () => LocalizedString
			/**
			 * government id is associated with another contract.
			 */
			duplicateGovernmentId: () => LocalizedString
			/**
			 * end date must be after start date.
			 */
			endDateAfterStart: () => LocalizedString
			/**
			 * end date is required.
			 */
			endDateRequired: () => LocalizedString
			/**
			 * end date
			 */
			endDateShort: () => LocalizedString
			/**
			 * please select a valid tenant.
			 */
			invalidTenant: () => LocalizedString
			/**
			 * loading tenant...
			 */
			loadingTenant: () => LocalizedString
			/**
			 * loading tenants...
			 */
			loadingTenants: () => LocalizedString
			/**
			 * no tenant found.
			 */
			noTenantFound: () => LocalizedString
			/**
			 * number of cycles
			 */
			numberOfCycles: () => LocalizedString
			/**
			 * payment amount must be greater than zero
			 */
			paymentAmountGreaterThanZero: () => LocalizedString
			/**
			 * payment amount is required
			 */
			paymentAmountRequired: () => LocalizedString
			/**
			 * payment date is required
			 */
			paymentDateRequired: () => LocalizedString
			/**
			 * pick a date
			 */
			pickDate: () => LocalizedString
			/**
			 * pick a date range
			 */
			pickDateRange: () => LocalizedString
			/**
			 * contract period must be a whole number of {days}-day {interval} cycles.
			 */
			periodMustMatchWholeCycles: (arg: { days: unknown, interval: unknown }) => LocalizedString
			/**
			 * search and select tenant
			 */
			searchAndSelectTenant: () => LocalizedString
			/**
			 * search tenant by name, id or phone...
			 */
			searchTenantPlaceholder: () => LocalizedString
			/**
			 * start date is required.
			 */
			startDateRequired: () => LocalizedString
			/**
			 * start typing to search tenants by name, id or phone.
			 */
			startTypingTenantSearch: () => LocalizedString
			/**
			 * tenant is required.
			 */
			tenantRequired: () => LocalizedString
		}
		hooks: {
			/**
			 * units added to contract successfully!
			 */
			assignUnitsSuccess: () => LocalizedString
			/**
			 * payment created successfully!
			 */
			createPaymentSuccess: () => LocalizedString
			/**
			 * contract created successfully!
			 */
			createSuccess: () => LocalizedString
			/**
			 * payment deleted successfully!
			 */
			deletePaymentSuccess: () => LocalizedString
			/**
			 * contract deleted successfully!
			 */
			deleteSuccess: () => LocalizedString
			/**
			 * unit removed from contract successfully!
			 */
			removeUnitSuccess: () => LocalizedString
			/**
			 * contract restored successfully!
			 */
			restoreSuccess: () => LocalizedString
			/**
			 * contract terminated successfully!
			 */
			terminateSuccess: () => LocalizedString
			/**
			 * payment updated successfully!
			 */
			updatePaymentSuccess: () => LocalizedString
			/**
			 * contract updated successfully!
			 */
			updateSuccess: () => LocalizedString
		}
		intervals: {
			/**
			 * annual
			 */
			annual: () => LocalizedString
			/**
			 * monthly
			 */
			monthly: () => LocalizedString
			/**
			 * quarterly
			 */
			quarterly: () => LocalizedString
			/**
			 * semi-annual
			 */
			semiAnnual: () => LocalizedString
		}
		payments: {
			/**
			 * this contract has already reached its required total payment amount. you can still edit or delete payments if needed, but you cannot add more until the paid total drops below the required amount.
			 */
			fullyPaidNotice: () => LocalizedString
			/**
			 * this contract has been fully paid. you can edit or delete payments, but you cannot add more.
			 */
			fullyPaidSummary: () => LocalizedString
			/**
			 * {percent}% fulfilled
			 */
			percentFulfilled: (arg: { percent: unknown }) => LocalizedString
			/**
			 * {amount} sar remaining
			 */
			remaining: (arg: { amount: unknown }) => LocalizedString
			/**
			 * terminated contracts are locked. you can review payment history here, but you cannot add, edit, or delete payments until the contract is unterminated.
			 */
			terminatedNotice: () => LocalizedString
			/**
			 * this contract is terminated and locked. payment records are read-only.
			 */
			terminatedSummary: () => LocalizedString
			/**
			 * payments
			 */
			title: () => LocalizedString
			/**
			 * payments for {govId}
			 */
			titleFor: (arg: { govId: unknown }) => LocalizedString
			/**
			 * track contract payments and add new payment records here.
			 */
			trackSummary: () => LocalizedString
		}
		statusDescriptions: {
			/**
			 * active; payments on track
			 */
			active: () => LocalizedString
			/**
			 * ended; not paid in full
			 */
			defaulted: () => LocalizedString
			/**
			 * ended; paid in full
			 */
			expired: () => LocalizedString
			/**
			 * active; paid in full
			 */
			fulfilled: () => LocalizedString
			/**
			 * scheduled; starts in the future
			 */
			scheduled: () => LocalizedString
			/**
			 * manually terminated; locked for changes
			 */
			terminated: () => LocalizedString
		}
		table: {
			/**
			 * payments management
			 */
			paymentsManagement: () => LocalizedString
			/**
			 * are you sure you want to remove the manual termination from this contract?
			 */
			restoreDescription: () => LocalizedString
			/**
			 * restore contract
			 */
			restoreTitle: () => LocalizedString
			/**
			 * are you sure you want to manually terminate this contract? this only works for active or past contracts.
			 */
			terminateDescription: () => LocalizedString
			/**
			 * terminate contract
			 */
			terminateTitle: () => LocalizedString
			/**
			 * tenant #{tenantId}
			 */
			tenantFallback: (arg: { tenantId: unknown }) => LocalizedString
			/**
			 * units management
			 */
			unitsManagement: () => LocalizedString
		}
		units: {
			/**
			 * remove a unit from this contract when it should no longer be linked to it.
			 */
			assignedDescriptionEditable: () => LocalizedString
			/**
			 * review the units currently linked to this contract.
			 */
			assignedDescriptionLocked: () => LocalizedString
			/**
			 * assigned units
			 */
			assignedTitle: () => LocalizedString
			/**
			 * choose a complex to show units that are available for this contract timeframe. units linked to overlapping contracts are excluded.
			 */
			availableDescription: () => LocalizedString
			/**
			 * available units
			 */
			availableTitle: () => LocalizedString
			/**
			 * loading contract...
			 */
			loadingContract: () => LocalizedString
			/**
			 * contracts with registered payments are locked. you can review linked units here, but you cannot assign or remove units after payments have been recorded.
			 */
			lockNoticeHasPayments: () => LocalizedString
			/**
			 * terminated contracts are locked. you can review linked units here, but you cannot assign or remove units until the contract is unterminated.
			 */
			lockNoticeTerminated: () => LocalizedString
			/**
			 * assign available units by complex, then manage the units already linked to this contract.
			 */
			lockSummaryDefault: () => LocalizedString
			/**
			 * this contract has registered payments. unit assignments are locked.
			 */
			lockSummaryHasPayments: () => LocalizedString
			/**
			 * this contract is terminated and locked. unit assignments are read-only.
			 */
			lockSummaryTerminated: () => LocalizedString
			/**
			 * no units are assigned to this contract yet.
			 */
			noAssignedUnits: () => LocalizedString
			/**
			 * no units are available for this contract timeframe in the selected complex.
			 */
			noAvailableUnits: () => LocalizedString
			/**
			 * select a complex to load available units.
			 */
			selectComplex: () => LocalizedString
			/**
			 * select complex
			 */
			selectComplexPlaceholder: () => LocalizedString
			/**
			 * units for {govId}
			 */
			unitsFor: (arg: { govId: unknown }) => LocalizedString
			/**
			 * units
			 */
			unitsTitle: () => LocalizedString
		}
	}
	settingsHooks: {
		/**
		 * backup created successfully!
		 */
		backupCreated: () => LocalizedString
		/**
		 * backup deleted successfully!
		 */
		backupDeleted: () => LocalizedString
		/**
		 * backup restored successfully!
		 */
		backupRestored: () => LocalizedString
		/**
		 * database path reset to default successfully!
		 */
		databasePathReset: () => LocalizedString
		/**
		 * database path updated successfully!
		 */
		databasePathUpdated: () => LocalizedString
		/**
		 * ending soon notice window updated successfully!
		 */
		endingSoonUpdated: () => LocalizedString
		/**
		 * protected update backup restored successfully!
		 */
		rollbackRestored: () => LocalizedString
		/**
		 * startup recovery cleared. retrying the current version is now allowed.
		 */
		startupRecoveryCleared: () => LocalizedString
	}
}

export type Formatters = {}
